### ISSUE TITLE
您好，能否在github上放一个编译好的APK文件呢？

### ISSUE THREAD

**Issue by zangbob** [Ashinch/ReadYou#1]
恰好昨天没看酷安，刚看到上架了，兴冲冲赶去时，已经被下架了。

能不能在github上放一个APK文件呢？  毕竟不是所有人都有电报账号的。。。

（说实话，真的不能理解，为什么一定要把预览版的APK放在TG... ）

**Comment by Ashinch** [comment]
准备 Release 了，之前是从零开始，并且没有版本号的，都是零碎更新，所以觉得不适合放到 GitHub Release。

**Comment by VergeDX** [comment]
也许可以做一个 GitHub Actions 自动 build 的工作流

**Comment by Ashinch** [comment]
> 也许可以做一个 GitHub Actions 自动 build 的工作流
> 
> Update: 注意到有 2 个 fork 已经做了上述工作：
> https://github.com/Ashinch/ReadYou/compare/main...HeWeiNianChu:main
> https://github.com/Ashinch/ReadYou/compare/main...kongbai39:main

收到，下版本开始会在Github Release中了
