### ISSUE TITLE
Some text in French are not correctly centered

### ISSUE THREAD

**Issue by Peaulixs** [Ashinch/ReadYou#104]
![Screenshot_20220607-035837.png](https://user-images.githubusercontent.com/62362754/172328504-a232eab6-efd9-40c9-a029-eb8dbd9423c7.png)

![Screenshot_20220607-035801.png](https://user-images.githubusercontent.com/62362754/172328523-573fb673-72d6-41c1-9e1e-6f4f01b5bdde.png)

**Comment by Ashinch** [comment]
Okay, I will fix it.
