### ISSUE TITLE
Add an option to star an article from the flow page

### ISSUE THREAD

**Issue by ch3thanhs** [Ashinch/ReadYou#106]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.8.1]

**2. Describe the feature request**

As a user I should be able to star an article from the flow page.

Currently if a user finds an article interesting and wants to star it - to read later, They have to first open the article and then star it. This is a two step process and also marks the article as read.

Instead there can be a pop-up after long pressing an article that would let the user star it.

**Comment by pc00per** [comment]
I think holding is a better way

**Comment by ch3thanhs** [comment]
Duplicate of #611

**Comment by ch3thanhs** [comment]
A new issue #611 seems to be covering this along with other options, will close this.

**Comment by JunkFood02** [comment]
> A new issue #611 seems to be covering this along with other options, will close this.

Also #586
