### ISSUE TITLE
对于防盗链图片能否增加一个代理设置？

### ISSUE THREAD

**Issue by 1gcat** [Ashinch/ReadYou#107]
目前我的解决方式是搭建一个代理，被代理的rss内容中的图片链接会被加上代理地址重新输出xml。
大概是这样：https://proxy.xxx.com/rss?url=rss地址
但是每次都要手动在订阅地址开头输入代理地址，有点麻烦，能否提供一个设置用于填写代理地址，在输入订阅地址界面提供勾选是否使用防盗链代理？
不然订阅了一些博客看不到图片有点难受~
另外，作者如果有其他更好的解决方式还请不吝赐教，感谢~

**Comment by Ashinch** [comment]
嗨 @1gcat ，

能否提供一个存在防盗链图片的rss链接，我去看看情况。

**Comment by 1gcat** [comment]
> 嗨 @1gcat ，
> 
> 能否提供一个存在防盗链图片的rss链接，我去看看情况。

比如这个博客的rss：https://hin.cool/atom.xml
