### ISSUE TITLE
The app is not fetching RSS feeds of YouTube channels

### ISSUE THREAD

**Issue by S-Sajith** [Ashinch/ReadYou#11]
![Screenshot_20220427-215203-770](https://user-images.githubusercontent.com/88919814/165566324-7c98886b-604a-40e7-a7cd-f81e74073566.png)
I use a youtube client called newpipe to create RSS feeds of certian youtube channels , but this app doesn't seem to fetch or recognize rss feeds of youtube channels created from newpipe.
![Screenshot_20220427-215809-710](https://user-images.githubusercontent.com/88919814/165567256-a231c76e-2bad-471d-9f5d-f2e8bf290c6d.png)

**Comment by S-Sajith** [comment]
https://www.youtube.com/feeds/videos.xml?channel_id=UCRcgy6GzDeccI7dkbbBna3Q

**Comment by S-Sajith** [comment]
also consider adding an option to open the links in an external browser or custom browser tab

**Comment by Ashinch** [comment]
> also consider adding an option to open the links in an external browser or custom browser tab, instead of the default reader built within the app . An option to choose a different default reader for each individual feed group would also be great.

You can click on its title, just like Reeder.

**Comment by Ashinch** [comment]
> https://www.youtube.com/feeds/videos.xml?channel_id=UCRcgy6GzDeccI7dkbbBna3Q

This is a known bug, and it will be fixed in the near future.

**Comment by S-Sajith** [comment]
ok thank you

**Comment by Ashinch** [comment]
#13
