### ISSUE TITLE
请求增加内置浏览器

### ISSUE THREAD

**Issue by zhusuner** [Ashinch/ReadYou#111]
能调用手机自带的webview就行，每次都要跳到浏览器很麻烦

**Comment by Ashinch** [comment]
👌

**Comment by Ashinch** [comment]
@klaxonz 设置 -> 交互 里面有

**Comment by klaxonz** [comment]
@Ashinch 找到了，后续能否针对订阅源，单独设置默认的打开方式？因为有些订阅源可能不输出全文，这时候需要点击多一次链接打开网页，如果进入阅读页能默认打开网页就更好了。

**Comment by Ashinch** [comment]
@klaxonz 这个需要后面再议了

**Comment by AustinZhang1024** [comment]
> [@klaxonz](https://github.com/klaxonz) 这个需要后面再议了

请问内置浏览器有没有便捷的方式切换，比如滑动或者双击等自动打开
