### ISSUE TITLE
The app doesn't seem to be fetching articles from these sources for some reason

### ISSUE THREAD

**Issue by S-Sajith** [Ashinch/ReadYou#12]
https://feeds.feedburner.com/variety/headlines

https://deadline.com/feed/

https://astronomy.com/rss/news

https://www.wired.com/feed

https://www.wionews.com/feeds/india-news/rss.xml

https://ftr.fivefilters.net/makefulltextfeed.php?url=jalopnik.com/rss&max=3&links=preserve

https://feeds.feedburner.com/carthrottle

https://www.autocarindia.com/rss/all

**Comment by Ashinch** [comment]
#13
