### ISSUE TITLE
Some feeds when opened only show imcomplete contents like

### ISSUE THREAD

**Issue by ansarimohammed422** [Ashinch/ReadYou#122]
**1. Environment**

-   Device: [Redmi note 4]
-   OS: [Android 12.1]
-   APP: [0.8.1]
- 
**2. Describe the bug**

Like

This article is long enough

![Screenshot_20220629-231821_Bromite](https://user-images.githubusercontent.com/78704469/176502999-5bb71cd2-d147-4903-9ca6-ba8de81f6a11.png)

But in read you it is shown imcompletely
Like this

![Screenshot_20220629-231845_Read You](https://user-images.githubusercontent.com/78704469/176503148-99783263-7884-4f2d-a2d7-67e65ea48184.png)

It is happening with every article of gizmochina
And some other feeds also

See into it

**Comment by Ashinch** [comment]
By default only the `<description>` and `<content>` parts of the feed are displayed, if the feed does not provide full content in these two items, you can click the `Parse Full Content` button in the bottom right corner.

**Comment by pc00per** [comment]
This should be closed by now.
