### ISSUE TITLE
Horizontal scroll on HTML pre text

### ISSUE THREAD

**Issue by esdnm** [Ashinch/ReadYou#124]
**1. Environment**

-   OS: [Android 10 Go]
-   APP: [0.8.1]

**2. Describe the bug**

HTML `<pre>` boxes has, what it looks like, a fixed width to all of them. The horizontal scroll on each  `<pre>` is not based on the max line width of each `<pre>` element. For most  `<pre>` text the horizontal scroller scrolls way past the last character of the widest line.

**Comment by Ashinch** [comment]
@esdnm Yes, this is a solution from Feeder, I can't think of a better one at the moment.

**Comment by esdnm** [comment]
> @esdnm Yes, this is a solution from Feeder, I can't think of a better one at the moment.

How can this be a solution? Is Android's UI so lacking in features?

**Comment by esdnm** [comment]
How does GitHub's Android app display HTML rendering of markdown? Is it a non-native app?
