### ISSUE TITLE
Fix scrolling at 0x animation speed

### ISSUE THREAD

**Issue by ghost** [Ashinch/ReadYou#130]
**1. Environment**

-   Device: `Redmi Note 10`
-   OS: `Android 12.1 (Lineage 19.1)`
-   APP: `0.8.1`

**2. Describe the bug**

I always have my animations disabled (Settings > Accessibility > Text & Display > Remove animations) rendering ReadYou animations & scrolling to 0x.
I can't enable my whole system animation speed just for ReadYou to scroll nicely.

**Comment by pc00per** [comment]
@Ashinch Btw, can you consider this issue for the next update? This is a huge critical problem for those who disable systemwide animations.

**Comment by Ashinch** [comment]
Sorry, it's not up to me to decide, you can open issue in the Jetpack Compose project

**Comment by pc00per** [comment]
> Sorry, it's not up to me to decide, you can open issue in the Jetpack Compose project

Okay. Btw I personally use many Material You apps that don't have this scroll issue. Infact, disabling animations shouldn't be affecting the scroll acceleration in the first place.

**Comment by pc00per** [comment]
Btw I relaised jetpack composer is a google's UI framework & I don't own a google account ingeneral. So I can't open issues in their issue tracker. I hope you or somebody else could do it.

**Comment by Ashinch** [comment]
@pc00per Those other apps you mentioned that use MDC are not built with Jetpack Compose.

**Comment by pc00per** [comment]
Is it not possible to set scroll animation to 1x in the framework config itself while building ?

**Comment by Ashinch** [comment]
@pc00per Hey, bro. This should be done by Google officials

**Comment by pc00per** [comment]
Perhaps maybe could you consider any alternative non google framework UI ?

**Comment by Ashinch** [comment]
@pc00per I won't think about it, because it's tantamount to starting from scratch.😢

**Comment by Ashinch** [comment]
@Ashinch Maybe Google will fix this in some Jetpack Compose update.

**Comment by pc00per** [comment]
I hope so

**Comment by pc00per** [comment]
Looks like no one had this issue yet.
https://issuetracker.google.com/issues?q=status:open%20componentid:192731&s=created_time:desc

**Comment by Ashinch** [comment]
@pc00per This may be as conventional as other related issues.

**Comment by pc00per** [comment]
v0.9.1 didn't yet included the jetpack compose merge fix. Did you update the framework btw ?

**Comment by Ashinch** [comment]
@pc00per I will update the compose dependency when the third-party API is supported, but there is no guarantee it will solve the issue. 🥲

**Comment by pc00per** [comment]
Oh okay. I wonder how many users exist who disable animations & experience this issue. Like literally, all the post Android 12 application projects started using JC. Even the ones under FDroid repositories...😐
I hope the above merge will propagate through all these projects.

**Comment by pc00per** [comment]
https://issuetracker.google.com/issues/241460890#comment12
The following release(s) address this bug:
**`androidx.compose.foundation:foundation:1.4.0-alpha01`**

**Comment by Ashinch** [comment]
@pc00per Okay, I will follow up soon

**Comment by Ashinch** [comment]
I am glad that the Material library supports controlling this feature through system animation speed in its 1.0.1 version. Read You to upgrade this dependency to the target version to resolve this issue.

#374
