### ISSUE TITLE
use system font instead of default `Google-Sans`

### ISSUE THREAD

**Issue by ghost** [Ashinch/ReadYou#136]
**1. Environment**

-   Device: Redmi Note 10
-   OS: Lineage 19.1 [Android 12.1]
-   APP: 0.8.1

**2. Describe the feature request**

Custom roms have luxury of changing fonts from settings as well as through Magisk Mods. Currently ReadYou doesn't follow those & render it's own default font.

**Comment by bakinazik** [comment]
we need an option for that.. current font really great tho

**Comment by pc00per** [comment]
This would also paves a way for a smaller app & avoid shipping font in the application.

**Comment by Ashinch** [comment]
#327
