### ISSUE TITLE
Initial Filter

### ISSUE THREAD

**Issue by bakinazik** [Ashinch/ReadYou#139]
**1. Environment**

-   Device: Honor 9 Lite
-   OS: Android 9
-   APP: 0.8.3

**2. Describe the bug**

initial filter not cached on startup. its happen latest version.

**Comment by Ashinch** [comment]
It has been fixed and will be released in the next version.

https://github.com/Ashinch/ReadYou/commit/4416b6792dc75f3c7f4bfc70abffdb3d80caeee2

**Comment by Ashinch** [comment]
#229
