### ISSUE TITLE
"On start" option does not work

### ISSUE THREAD

**Issue by Darkempire78** [Ashinch/ReadYou#151]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.8.3]

**2. Describe the bug**

The setting "On start" (initial page and initial filter) do not work

My settings :
![Screenshot_20220716-123752](https://user-images.githubusercontent.com/50015928/179351622-87bbd8d8-7c6c-476f-9037-5a281df405e9.png)

The page (and filter) when I open (after closing the app) :
![Screenshot_20220716-123741](https://user-images.githubusercontent.com/50015928/179351659-6135afc1-04b3-493a-93b4-4b919aeda229.png)

**Comment by Ashinch** [comment]
#139

Yes, it's a bug with version 0.8.3

**Comment by Ashinch** [comment]
#229
