### ISSUE TITLE
Many articles have no image in the list of articles while there is an image in the rss feed

### ISSUE THREAD

**Issue by Darkempire78** [Ashinch/ReadYou#154]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.8.3]

**2. Describe the bug**

Several articles have no image in the list of articles while there is an image in the rss feed.

e.g : https://www.lemonde.fr/rss/une.xml

There are <media:content> balises with an image but Read You does not display it in the article list

**Comment by Ashinch** [comment]
Some case have been fixed.
