### ISSUE TITLE
Ability to edit the nanes of the sites

### ISSUE THREAD

**Issue by scientiac** [Ashinch/ReadYou#168]
Apparently some feeds don't include the website's name, so an option to manually input the name or better edit the names would
![Screenshot_20220803-201546_Read You](https://user-images.githubusercontent.com/58177655/182639494-64d3cb0c-74de-4d9e-9b09-3423543c9a41.png)
 be handy.

**Comment by wsu808** [comment]
You can edit the name manually:  
- Long-press this field
- click on the name (or rather the place where name should appear)  
![Screenshot_20220819122239](https://user-images.githubusercontent.com/26609859/185598811-28e74da6-4cc2-4fe6-ba4f-337cded9f38a.jpg)

It will let you edit the name but I am not sure whether you will be able to click this field it it's completely empty (so it has 0 width) ...

**Comment by wsu808** [comment]
Yeah, it's probably a bug then. 
(It is also possible to edit name when adding new feed, but it would probably be the same case and it won't let you edit it then either. But of course you can try it.)

You may leave the link to this rss feed so developer may test it himself.

**Comment by Ashinch** [comment]
Done
