### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [Ashinch/ReadYou#173]
https://hosted.weblate.org/projects/readyou/#information says AGPLv3-only, whereas
https://github.com/Ashinch/ReadYou/search?q=any+later says or later.

Would be compatible if it is made AGPLv3-or-later (AGPLv3+) in

https://hosted.weblate.org/settings/readyou/android-strings/
https://hosted.weblate.org/settings/readyou/f-droid-and-play-store-metadata/
https://hosted.weblate.org/settings/readyou/glossary/

Would also make  a point to change it in the README

**Comment by Ashinch** [comment]
Sorry, this was a selection error and has now been changed to the same AGPLv3-or-later

**Comment by comradekingu** [comment]
@Ashinch Should also be changed for
https://hosted.weblate.org/projects/readyou/glossary/
in
https://hosted.weblate.org/settings/readyou/glossary/

**Comment by Ashinch** [comment]
Done
