### ISSUE TITLE
ReadYou is translated to 2 Weblate instances `?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Ashinch/ReadYou#180]
https://weblate.bubu1.eu/projects/readyou/

https://hosted.weblate.org/projects/readyou/

Why `?

**Comment by Ashinch** [comment]
@mondlicht-und-sterne https://hosted.weblate.org/projects/readyou/

**Comment by mondlicht-und-sterne** [comment]
https://weblate.bubu1.eu/projects/pt-br-translation-of-the-read-you-android-app/#components

https://weblate.bubu1.eu/projects/readyou/

And who removes that ? You ? or should I tell the Instanue Admin  of weblate.bubu1.eu ?

But I find something strange

**Comment by Ashinch** [comment]
@mondlicht-und-sterne It has been removed
