### ISSUE TITLE
Change font from Google Sans

### ISSUE THREAD

**Issue by noClaps** [Ashinch/ReadYou#181]
I wasn't sure which category this would fall into, so I just opened a blank issue. Sorry about that.

I just wanted to say Google Sans is under a proprietary license and not available for use by developers. Refer to: https://github.com/flutter/flutter/issues/18266#issuecomment-395482313

Maybe you should consider using a font with an open source license instead. [Inter](https://rsms.me/inter/) is a really good looking font. [Manrope](https://www.manropefont.com/) is another really good font that looks a bit more like Google Sans.

**Comment by xIUPITERx** [comment]
@Ashinch 

This is extremely important. 
In Germany there have already been very high fines imposed on developers because of this.

**Comment by Ashinch** [comment]
@xIUPITERx Thanks for the heads up, I'll be replacing it with an open source font soon

**Comment by Ashinch** [comment]
#327
