### ISSUE TITLE
Monochrome icon seems weird 

### ISSUE THREAD

**Issue by asuka-mio** [Ashinch/ReadYou#187]
![Screenshot_20220819-103543~2](https://user-images.githubusercontent.com/43900799/185530743-a32a8908-51e9-4442-9179-e5e4c558a011.png)

**Comment by asuka-mio** [comment]
Maybe fixed in https://github.com/Ashinch/ReadYou/commit/9dcf7b8db80b6fb1618deef723d2ffcdf9071c41
Closed

**Comment by Ashinch** [comment]
@asuka-mio A fix has been committed, you can test this build: https://github.com/Ashinch/ReadYou/actions/runs/2884074350

**Comment by asuka-mio** [comment]
> @asuka-mio A fix has been committed, you can test this build: https://github.com/Ashinch/ReadYou/actions/runs/2884074350

![Screenshot_20220819-104118~2](https://user-images.githubusercontent.com/43900799/185531386-e17e65d8-cece-4cb6-90e7-ef28c83cc2ff.png)
It looks normal now, thx!
