### ISSUE TITLE
Add text to bottom bar

### ISSUE THREAD

**Issue by Donkey-Doug** [Ashinch/ReadYou#19]
Follow the google guidelines for bottom bars and add text. For example:

![redditsync-tjlzi4](https://user-images.githubusercontent.com/50382414/166059675-090b3f33-c4ab-44db-be74-1574dabd635d.jpg)

**Comment by Ashinch** [comment]
This will be toggleable in the settings.

**Comment by Donkey-Doug** [comment]
Also, your icons are not very intuitive.
