### ISSUE TITLE
Read aloud articles

### ISSUE THREAD

**Issue by jcperil** [Ashinch/ReadYou#201]
**1. Environment**

-   OS: [Android 12]
-   APP: [0.8.3]

**2. Describe the feature request**

Reading articles aloud similar to the read aloud feature in [Feeder](https://gitlab.com/spacecowboy/Feeder).

**Comment by candideu** [comment]
Here's another excellent open-source read aloud software with many reading voices: https://github.com/ken107/read-aloud

**Comment by Ashinch** [comment]
Temporary solution: Utilize the ability to read aloud in Webview. #568
