### ISSUE TITLE
Add global cleaning tool and option to only delete articles that are older

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [Ashinch/ReadYou#203]
**2. Describe the feature request**

There are only options to clear articles ler group and feed currently. A global cleaning option popup with an icon perhaps at the top right (in the case of global cleaning) in the main interfacr could solve this best. We should be able to set the age we want to delete articles from, only delete articles that are read (as described in #199) in or both etc. This option should not only be accessible for global cleaning bot for per group and feed deletions too.

**Comment by Ashinch** [comment]
#185
