### ISSUE TITLE
Themed Icon Enlarged

### ISSUE THREAD

**Issue by Hothomir** [Ashinch/ReadYou#209]
**1. Environment**

-   Device: [Pixel 5]
-   OS: [Android 13]
-   APP: [0.8.3]

**2. Describe the bug**

There seems to be an issue where the app icon Is enlarged when Themed Icons are turned on at the system level. Here is what it looks like when that is on:

![Screenshot_20220831-093843.png](https://user-images.githubusercontent.com/10063060/187692341-6aabee76-4ff3-4faf-9f9c-a7bd4a2e18ee.png)

And here's what it looks like when Themed Icons are off:
![Screenshot_20220831-093859.png](https://user-images.githubusercontent.com/10063060/187692403-770ae161-b820-4179-8a31-247d840394c4.png)

**Comment by chengnan049** [comment]
This bug will fix in next version.

**Comment by Hothomir** [comment]
Awesome!

**Comment by Ashinch** [comment]
#185
