### ISSUE TITLE
Allow copying url links inside articles

### ISSUE THREAD

**Issue by jcperil** [Ashinch/ReadYou#213]
**1. Environment**

-   OS: [Android 12]
-   APP: [0.8.3]

**2. Describe the feature request**

Allow copying url links in articles. Currently, if I press hold on any links, it provides the user to copy the link text and not the link address.

**Comment by jcperil** [comment]
Any update on this? It would be a useful feature being able to copy internal links inside articles.

**Comment by yue-dongchen** [comment]
I have the same request. I think long-pressing the title is a good solution.

**Comment by yue-dongchen** [comment]
Sorry I didn't carefully read the issue description. For me it is regarding the link to the article itself.
