### ISSUE TITLE
Tips for Google Reader API synchronisation

### ISSUE THREAD

**Issue by Alkarex** [Ashinch/ReadYou#221]
Hello,
A FreshRSS user has just [made me aware](https://github.com/FreshRSS/FreshRSS/pull/4633) of the work in progress here with ReadYou.

I have not checked how far you are implementing Google Reader API support, but here are some tips / recommendations regarding what API calls to make for an efficient synchronisation strategy:

https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776

Indeed, over the years, I have seen many newly-developed apps, most of them with bad synchronisation performance, so I hope those tips will be useful in order for ReadYou not to fall in the same traps  🤓

**Comment by Ashinch** [comment]
Thanks 🙏 
I'll try it.

**Comment by gbakeman** [comment]
I just came here from issue #94, and it does indeed appear that the Google Reader API is superior to the Fever API. Hopefully #94 can be closed and this one (Google) will be implemented.

**Comment by Ashinch** [comment]
I will close this issue when I finish the GoogleReader API

**Comment by AndreaDiNapoli** [comment]
Do you have an ETA for this feature?
I think your app is possibly the best around and cannot wait to be able to use it with my freshrss instance.

Thank you for your work :)

**Comment by AndreaDiNapoli** [comment]
So cool, can't wait to test it!
