### ISSUE TITLE
Unable to unselect text 

### ISSUE THREAD

**Issue by orbisvicis** [Ashinch/ReadYou#226]
**1. Environment**

-   Device: [Pixel 4]
-   OS: [Android 13]
-   APP: [0.8.3]

**2. Describe the bug**

Normally you can click outside of selected text to unselect the text. In this app, the only way to unselect text and remove the selected text highlight, is to press the copy button.

**Comment by JunkFood02** [comment]
https://issuetracker.google.com/issues/254079910

**Comment by SNAKESLIGHT** [comment]
This seems to only effect parts of some articles because I can select and deselect text on the first paragraph of one article but not the rest of it. And on some I can't deselect anywhere.

**Comment by prurigro** [comment]
I've been hitting this as well- strangely there was one time where I was able to de-select the text but I'm not sure what it was.

Is the logic that includes the Modifier.pointerInput+detectTapGestures just to handle inline links? I assume it's the one in app/src/main/java/me/ash/reader/ui/component/reader/ClickableTextWithInlineContent.kt?

**Comment by JunkFood02** [comment]
> I've been hitting this as well- strangely there was one time where I was able to de-select the text but I'm not sure what it was.
> 
> Is the logic that includes the Modifier.pointerInput+detectTapGestures just to handle inline links? I assume it's the one in app/src/main/java/me/ash/reader/ui/component/reader/ClickableTextWithInlineContent.kt?

Yes, this only happens with text sections with inline links. Compose Text team has already released a new `Text` component with `LinkAnnotation` in their beta release which could solve this issue. We'll migrate to the new implementation once it hit stable

**Comment by nathan-contino** [comment]
Any news on updating the Compose Text `Text` component? If not, I'd be happy to try to fix it with some modifications to the inline link handling.

**Comment by Ashinch** [comment]
This is a bug in compose, maybe you can try Webview Renderer #568
