### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by Donkey-Doug** [Ashinch/ReadYou#24]
Make it possible to customize the layout. For example,

- Image on the left or right.
- Large card-style centered image with the headline either above or below the image.
- Large card-style centered image with the headline on top of the image. Add shadow around white text to remain readable.
- Change padding around images. Let the user choose vertical and horizontal padding. Make it possible for content to reach the sides of the screen (0 horizontal padding) and completely eliminate the space between articles (0 vertical padding).
- Two or more columns of articles. Particularly useful for landscape mode.
- Hide/show the source.
- Show/hide preview text.

**Comment by Ashinch** [comment]
Custom layout styles will allow change in the settings, but I'm not sure if all of the above features can be implement, so I'll close this Issue when some custom layout options are available.

**Comment by Donkey-Doug** [comment]
Just some ideas. No need to implement all. I would say having images and hiding preview text is already very useful.

**Comment by ildar** [comment]
Please reopen.
I really want the Card view. Like in [Feedme](https://play-lh.googleusercontent.com/TbUB3gYCCrg0WIQpG4pDAJEggqTNmyD8DcG6EEvb70ykJ-fNzb3DxvmuXFu4Z7L3li49=w526-h296)

**Comment by Ashinch** [comment]
@ildar Hey, the card view please open a new issue.
