### ISSUE TITLE
Article Thumbnails

### ISSUE THREAD

**Issue by nikhilCad** [Ashinch/ReadYou#270]
**1. Environment**

-   Device: [Moto E7 Powee]
-   OS: [Android 10]
-   APP: Latest

**2. Describe the feature request**

Many feeds provide a thumbnail for each of their articles, it should be shown in the apps. See : https://f-droid.org/packages/com.nononsenseapps.feeder/

**Comment by xIUPITERx** [comment]
It should have been implemented.

**Comment by Maell1** [comment]
For example : 
https://www.clubic.com/feed/news.rss

<enclosure url="https://..." type="image/jpeg" length="0"/>

There are no picture with ReadYou.
The  picture is show with Feeder.

**Comment by JunkFood02** [comment]
Fixed in #669
