### ISSUE TITLE
Logger Found in Read You

### ISSUE THREAD

**Issue by IronCR7** [Ashinch/ReadYou#274]
I have warden installed in my phone. Recently I've found this beautiful rss reader called "Read You" in f-droid and just loved 😍 it. But after scanning with 
![20221211_202112](https://user-images.githubusercontent.com/120319801/206909648-74fa69f6-275e-4979-9b58-8ce72087f295.jpg)
warden, found 1 logger. This concerns my privacy.  Could you please explain 🙏. Sorry for putting this into issues 😅

**Comment by Ashinch** [comment]
@IronCR7 [Logger] is used to output debug log messages to the terminal.

As you know, Read You is in the debugging phase of development and needs logging information to locate the cause of errors.

Theoretically, if some applications have obtained [root] privileges, they can indeed listen.

Currently the only sensitive information in the logs output by Read You is the [article], and you are right, I will remove it in the next release.
