### ISSUE TITLE
Automatically download full articles

### ISSUE THREAD

**Issue by CyberaxAnnon** [Ashinch/ReadYou#29]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.7.2]

**2. Describe the feature request**
To have the option to have a website or group specifically be labeled to always download articles and reading them without needing to go online after downloading. This should be a toggle within the settings and possibly pictures (but not required) if requested.

**Comment by Ashinch** [comment]
Currently feeds or groups have a toggle for default full content parsing.

If download the article content during the sync, this may cause the sync to take too long.

There will be a toggle to turn this feature on or off.

**Comment by Donkey-Doug** [comment]
Already implemented in latest update. Please close.
