### ISSUE TITLE
[Remove Logger] in next release.

### ISSUE THREAD

**Issue by IronCR7** [Ashinch/ReadYou#296]
Sir don't get me wrong but you said that you would remove the logger in this release but you haven't. This logger creates a privacy concern 😟. ![20230102_120226.jpg](https://user-images.githubusercontent.com/120319801/210200778-b969f5ff-ddf8-49a6-8fd9-156f7974afa6.jpg) ![20230102_120208.jpg](https://user-images.githubusercontent.com/120319801/210200853-22e459c7-f5a6-4700-b2b9-7e1a4bc70e6d.jpg)

**Comment by Ashinch** [comment]
@IronCR7 This is just a log output module integrated in other underlying dependencies and cannot be removed.

BTW, I have removed some sensitive outputs, and there are no privacy concerns you are worried about.

[https://github.com/arcao/slf4j-timber](https://github.com/arcao/slf4j-timber)
