### ISSUE TITLE
[Fever API] login fails with error 'Not valid credentials'

### ISSUE THREAD

**Issue by Elbullazul** [Ashinch/ReadYou#299]
**1. Environment**

-   Device: Pixel 6 Pro
-   OS: Android 13 (Calyx OS)
-   APP: 0.9.6

**2. Describe the bug**

Fever login fails with 'Not valid credentials' message. I tried the same login info in Fluent Reader and it worked.

**Comment by Ashinch** [comment]
@Elbullazul is F-Droid version?

**Comment by Ashinch** [comment]
@Elbullazul If you didn't install it from F-Droid, please go to GitHub release and reinstall ReadYou-0.9.6-c0ff8ba.apk

**Comment by Elbullazul** [comment]
@Ashinch I had installed the app from F-droid. The Github APK logs in normally. Thanks for the help 🙂

**Comment by Ashinch** [comment]
@Elbullazul Other F-Droid users should wait for the additional update from 0.9.7. This issue will be closed when 0.9.7 is released.

**Comment by Ashinch** [comment]
Version 0.9.7 has been committed, just wait for F-Droid to distribute it.

**Comment by lbwstco** [comment]
F-Droid version 0.9.7 same toast 'Not valid credentials', server is tiny-tiny-rss.

**Comment by Ashinch** [comment]
@lbwstco Waiting for feedback from a user who was able to successfully add an account

**Comment by th0mcat** [comment]
0.9.7 works for me with FreshRSS.  You need to make sure you use `https://<your.domain>/api/fever.php` as the Server URL, and then use the **API password** instead of your user password.

**Comment by nxmx** [comment]
I've successfully added a fever account in F-Droid's 0.9.7. Had to include the trailing '/' on the server url, failed without it.

**Comment by lbwstco** [comment]
> @lbwstco Waiting for feedback from a user who was able to successfully add an account

It's ok to add account, but pull failed.

**Comment by M86xKC** [comment]
I still faced this issue on the most recent version v0.9.8 @Ashinch

**Comment by M86xKC** [comment]
> I am able to log in, but no articles are loaded, even though there are plenty of unread ones.

You can create a new issue for that I guess with the error message that you get, or if you have access to logs.

This issue is specific to not being able to login when not having a trailing "/" at the end of the fever api endpoint

Meaning `example.com/fever` does not work
but `example.com/fever/` works without issues

**Comment by lepanen** [comment]
There are no error messages and I don't have access to logs. Log in doesn't work of there is no trailing "/", so that is needed and is added. I am able to log in, and folders are loaded, but no sources or articles.

**Comment by th0mcat** [comment]
If you're pointing ReadYou at a FreshRSS install, you have to make sure you type out the location of the Fever API endpoint.

![Screenshot_20230516-105211](https://github.com/Ashinch/ReadYou/assets/37344783/94027f83-40fd-497e-8454-46e25a5de8d0)

Make sure you are appending `/api/fever.php` to the end of the URL

**Comment by lepanen** [comment]
I'm using Fever in TT-RSS plugin
![Screenshot_20230516-192127](https://github.com/Ashinch/ReadYou/assets/123079430/567f9e6c-85af-491d-b941-dc19be44fbe7)

**Comment by th0mcat** [comment]
Are you redirecting to https via nginx/apache, or are you only using http/port 80?

**Comment by lepanen** [comment]
That's difficult for me to answer as this is not my own server, but I try to clear it up

**Comment by lepanen** [comment]
That I know won't work, as I haven't set that up

**Comment by lepanen** [comment]
I have set the password in Fever pugin, and I am using that in Read Me. 

Here are some logs from server, when the Read Me tries to fets groups and feeds.

  -   - - [16/May/2023:19:02:57 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:02:58 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:03:22 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:03:22 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:03:41 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 228 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:03:56 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:03:56 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:10:06 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:10:06 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:41:57 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:41:57 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:45:12 +0300] "POST /tt-rss/plugins.local/fever/?api=&groups HTTP/1.1" 200 654 "-" "ReadYou / 0.9.8(19)"
  -   - - [16/May/2023:19:45:13 +0300] "POST /tt-rss/plugins.local/fever/?api=&feeds HTTP/1.1" 200 7328 "-" "ReadYou / 0.9.8(19)"

**Comment by lepanen** [comment]
> Are you redirecting to https via nginx/apache, or are you only using http/port 80?

Now I understood this question. I'm only using http
