### ISSUE TITLE
[Bug or Internet Problem] techpowerup无法订阅

### ISSUE THREAD

**Issue by Moderpach** [Ashinch/ReadYou#3]
![Screenshot_20220419-231950_Pixel 启动器](https://user-images.githubusercontent.com/34941512/164038776-94508728-e870-4a27-a1ed-4ba79b12f611.png)

**Comment by Ashinch** [comment]
https://www.techpowerup.com/rss/news
https://www.techpowerup.com/rss/reviews

会不会是链接输入错了

**Comment by Moderpach** [comment]
可以了，谢谢
