### ISSUE TITLE
Search bar for keywords to articles

### ISSUE THREAD

**Issue by ghost** [Ashinch/ReadYou#30]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.7.2]

**2. Describe the feature request**
When searching articles read, unread or archived with a search bar so you can find an articles you can look for if so desired.

**Comment by jnolan7599** [comment]
Yes, please. The ability to search globally, read, unread as options would be a boon for those who are 'on the road' but know they'll have to find the article later even if its not an apparent 'favourite' at that moment.
