### ISSUE TITLE
小建议:代码高亮和大图查看

### ISSUE THREAD

**Issue by JohnsonTam9527** [Ashinch/ReadYou#300]
**1. Environment**

-   Device: [Redmi]
-   OS: [Android 10]
-   APP: [0.9.6]

**2. Describe the feature request**

(Want you've done some research before now)

* 文章内的代码块内的代码字体颜色和正文颜色一样, 是否可以添加代码高亮的功能, 这样看起来舒服些.
* 有时查看图片时会因为图片太小看不清里面的文字, 是否可以添加一个双击图片查看大图的功能.

**Comment by Ashinch** [comment]
@JohnsonTam9527 目前实现不了，原网页上的样式已经提前被可读性插件过滤掉了

**Comment by Ashinch** [comment]
@Ashinch 大图在计划，高亮以后再看吧

**Comment by JohnsonTam9527** [comment]
@Ashinch 感谢回复, 期待以后的版本.
