### ISSUE TITLE
Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by Evilhotdog** [Ashinch/ReadYou#312]
**1. Environment**

-   Device: Fairphone 4
-   OS: CalyxOS 4.5.0
-   APP: 0.9.6

**2. Describe the bug**
When attempting to read Planet KDE (or any group containing Planet KDE articles (perhaps a single offending article), no articles are visible, with the following error:
Row too big to fit into CursorWindow
requiredPos = 14, totalRows = 15

**Comment by zabir128** [comment]
Im getting the same error today in v 0.9.8. It was working nice untill today. Just one rss link, others are ok. Giving this error while entering the that link: 
"Row too big to fit into CursorWindow
requiredPos = 104, totalRows = 105"

It is not device specific. It is giving the same error in another device.

**Comment by zabir128** [comment]
I cleared the contents of the link, now refreshed todays rss contents with no proplem.

so the temporary solution: clear the feeds/contents/aticles of that link.

**Comment by kermes** [comment]
Getting the same in one of my feeds. Clearing content and refreshing doesn't work.
It's probably a single article that's causing this so once it's not present in the live feed anymore I guess clearing and refreshing will work again.... until they add an aritcle the exceeds whatever limit there's in sqlite
```
Row too big to fit into CursorWindow
requiredPos = 44, totalRows = 45
```

**Comment by mbestavros** [comment]
This one might be tricky to track down, from a quick look into the codebase. It seems like the toast message comes from an uncaught exception, but from where isn't immediately obvious.

If one of the people on the thread is able to provide logs when they encounter the bug, that would be extremely helpful, I'm sure.

**Comment by mbestavros** [comment]
Ah, looks like it's a bigger issue than Read You: https://github.com/andpor/react-native-sqlite-storage/issues/364

@Ashinch We could try implementing this fix? https://github.com/andpor/react-native-sqlite-storage/issues/364#issuecomment-1515889255

**Comment by kermes** [comment]
Nice catch @mbestavros 

I don't have access to android studio right now to check the logs, but if it helps, this is the feed failing for me right now:
https://www.newtral.es/feed/

**Comment by mbestavros** [comment]
Aha! Found it! This is the database function that's causing the bug: https://github.com/Ashinch/ReadYou/blob/main/app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt#L482

Thank you @kermes, that was extremely helpful!

**Comment by mbestavros** [comment]
@Ashinch Do you think it's worth trying the above fix I linked to?

If you'd like to, let's try and get that in before our next bugfix release. If not, I'll just cut a release with the SVG fix.

**Comment by Ashinch** [comment]
> @Ashinch Do you think it's worth trying the above fix I linked to?
> 
> If you'd like to, let's try and get that in before our next bugfix release. If not, I'll just cut a release with the SVG fix.

@mbestavros 

This issue is related to paging and seems challenging. In the next version, we can include SVG and other fix patches.

**Comment by mbestavros** [comment]
@Ashinch Sounds good. Are there any other bugfixes on the horizon? I'm inclined to push out one last update with the SVG fix this week if there's nothing imminent. It should give users a relatively stable build while we wait for other fixes/features to cook.

**Comment by Ashinch** [comment]
> @Ashinch Sounds good. Are there any other bugfixes on the horizon? I'm inclined to push out one last update with the SVG and swipe fixes this week if there's nothing imminent. It should give users a relatively stable build while we wait for other fixes/features to cook.

@mbestavros 

Yeah, it seems there are no urgent bugs that need fixing at the moment.

**Comment by mbestavros** [comment]
@Ashinch Awesome! I'm happy to draft a release tomorrow morning (it's late where I am) if you'd like, but also happy to defer to you.

**Comment by mbestavros** [comment]
PR #523 is a pretty effective workaround for this, but we may want to leave it open for further investigation. @Ashinch I'll leave the final decision up to you.

**Comment by Ashinch** [comment]
> PR #523 is a pretty effective workaround for this, but we may want to leave it open for further investigation. @Ashinch I'll leave the final decision up to you.

@mbestavros 

Certainly, if you manage to reproduce the issue and confirm the fix works, I don't think it's necessary to worry.

**Comment by kermes** [comment]
I just downloaded the last release and can confirm the fix is working.
Thanks a lot @mbestavros that was surprisingly fast, thank you for
checking, debugging and fixing so quickly!
