### ISSUE TITLE
Unable to close dialogs by tapping outside or pressing the back button

### ISSUE THREAD

**Issue by Lzmxya** [Ashinch/ReadYou#315]
**1. Environment**

-   Device: [Pixel 4]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the bug**

When go to **Settings** > **Accounts** > **Add accounts** and tap **Local** or **Fever**, a text field dialog for adding account will pop up. Currently the only way to leave it without adding an account is to tap **Cancel** button, but it should also be able to be closed by clicking outside of the dialog or by pressing the back button.

**Comment by Ashinch** [comment]
@Lzmxya You are right
