### ISSUE TITLE
Request: E-Reader Mode

### ISSUE THREAD

**Issue by rettgerst** [Ashinch/ReadYou#324]
**1. Environment**

-   Device: [ONYX BOOX Poke 4 Lite]
-   OS: [Android 11]
-   APP: [0.9.7]

**2. Describe the feature request**

I recently got an Android E-Reader with an E-Ink display to replace my Kindle, and I've been shopping around for an RSS app that behaves similarly to Reeder on iOS. ReadYou is a good reader and supports my cloud service (self-hosted Miniflux). However, scrolling on this device is a bad experience due to the low refresh rate and ghosting, and I would like an option for ReadYou to support a paginated reading view with tap zones to turn the page with no animation, similar to Kindle or many e-reading apps.

I imagine many users of conventional phones and tablets would also appreciate this option as well.

**Comment by mbestavros** [comment]
Jumping in to voice my support for this feature! Glad to see it being worked on as part of https://github.com/Ashinch/ReadYou/pull/356.

Just to confirm @Ashinch, do you plan on implementing a paginated reading view with #356? That feature, more than just reducing animations, is what's really crucial to make ReadYou better on e-readers IMO.

**Comment by Ashinch** [comment]
I am glad that the Material library supports controlling this feature through system animation speed in its 1.0.1 version. Read You to upgrade this dependency to the target version to resolve this issue.

Tablet view is in the interface reconstruction plan, and it will not be implemented quickly for now.
