### ISSUE TITLE
OOM error during sync (Fever API)

### ISSUE THREAD

**Issue by gryphonmyers** [Ashinch/ReadYou#326]
**1. Environment**

-   Device: Xiaomi Poco X3 NFC
-   OS: MIUI 12.5.4 (Android 11)
-   APP: 0.9.7 (F-Droid version)

**2. Describe the bug**

Using the Fever API with FreshRSS endpoint, sometimes while syncing I get a "failed to allocate memory" error then all my articles disappear. If I go to look at the feed again it will keep showing the OOM error until I relaunch / resync.

**Comment by Ashinch** [comment]
Hi, can you recall approximately how many articles were on your FreshRSS at that time?

**Comment by gryphonmyers** [comment]
> Hi, can you recall approximately how many articles were on your FreshRSS at that time?

My main stream has 31,000 articles in it

**Comment by gryphonmyers** [comment]
Worth noting that during sync, I see old articles reappearing at the top of the feed, as if it's starting from scratch re-rendering every article. Performance is also noticeably sluggish during sync - if I try to read articles there is a lot of lag, then it eventually crashes with the OOM error described above
