### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by cattopo** [Ashinch/ReadYou#332]
**1. Environment**

-   Device: [OnePlus MT2110]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the feature request**

去掉底栏图标点击时出现的白色方框, 有点影响视觉效果
![6255776023501190415_121](https://user-images.githubusercontent.com/96364755/216053640-e5c7e5e1-057e-40f6-9ab9-de30c3743c32.jpg)

**Comment by jjjjbow** [comment]
你的提议好像没有被采纳啊
