### ISSUE TITLE
An option to customize corner radius of article images

### ISSUE THREAD

**Issue by tvnmguy** [Ashinch/ReadYou#340]
An option to customize corner radius of article images

![IMG_20230214_090345.jpg](https://user-images.githubusercontent.com/116799295/218632541-6c6fdde9-563b-4a8a-bb3d-9a19784fec10.jpg)

**Comment by Ashinch** [comment]
Hi, @tvnmguy 

This is ReadYou's main visual design, and usually we don't change it.

But we can modify the rounded corners of the images in the reading page.
