### ISSUE TITLE
Failed to import OPML with categories

### ISSUE THREAD

**Issue by WXGopher** [Ashinch/ReadYou#343]
**1. Environment**

-   Device: XIAOMI 13 PRO
-   OS: MIUI 14
-   APP: 0.9.7

**2. Describe the bug**

Import from OPML does not import anything.

I guess this might be because I used an OPML file **with categories**. Here is what I've used
https://github.com/WXGopher/gopher-awesomeness/blob/master/resources/my_rss_subscription.opml
This file has been verified to be compatible with Planery and Feeder .

Thanks.

**Comment by WreckingBANG** [comment]
Same problem here

**Comment by Ashinch** [comment]
[#ddc7220](https://github.com/Ashinch/ReadYou/commit/ddc72209785076baf1708b48f842a24824084938)

**Comment by Naadiyaar** [comment]
@Ashinch i'm using version 9.8 from Fdroid and still having this issue.
the opml file seems ok, but when I try to add it nothing happens
