### ISSUE TITLE
ReadYou doesn't remember the location on the page

### ISSUE THREAD

**Issue by ikanakova** [Ashinch/ReadYou#346]
**1. Environment**

-   Device: Samsung Galaxy A53 5G (Nokia 6.1 as well)
-   OS: Android 13 (Android 10 as well)
-   APP: 0.9.7

**2. Describe the bug**
1. Reading and scrolling down the page.
2. Interrupting reading and lock the phone.
3. Unlocking the phone, the app will sometimes return to where it's supposed to.
4. Lock the phone again and ReadYou jumps to the top of the article.
- The article list behaves the same way.

**Comment by zhusuner** [comment]
+1

**Comment by fuleost** [comment]
这问题真的很影响使用了 哪位大佬能修修啊 跪求🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by Ashinch** [comment]
@fuleost 在我印象中已经修过了？🥲
