### ISSUE TITLE
possibility to export opml 

### ISSUE THREAD

**Issue by paulle** [Ashinch/ReadYou#348]
-   Device: [xperia 5 III]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the feature request**
Possibility to export opml
_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by WreckingBANG** [comment]
As far as i know, this is already a feature. 

1. Settings
2. Accounts
3. ReadYou(Local)
4. Export as OPML

If you want to then import it again, it might not work because of #343

**Comment by Ashinch** [comment]
[#ddc7220](https://github.com/Ashinch/ReadYou/commit/ddc72209785076baf1708b48f842a24824084938)

**Comment by Ashinch** [comment]
Settings -> Account -> Export As OPML file
