### ISSUE TITLE
Fever problems

### ISSUE THREAD

**Issue by wayner6** [Ashinch/ReadYou#355]
**1. Environment**

-   Device: [IQOO neo5 lite]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the bug**

I am using **self-host service** like TTRSS, i can't see my articles unread after i add my fever to this app. I just see my custom groups.
![Screenshot_20230306_105540.jpg](https://user-images.githubusercontent.com/88063517/223009480-5c8ede6a-82d0-4e7b-a20c-1208601142ae.jpg)

**Comment by wayne3602** [comment]
The same time,.i can see my subscribed articles unread in [Fluent Reader](https://github.com/yang991178/fluent-reader-lite), you can refer its code.

![Screenshot_20230306_110512.jpg](https://user-images.githubusercontent.com/88063517/223010445-56da0c04-3fbb-4f7c-901d-f6fa78eb9a26.jpg)

**Comment by Ashinch** [comment]
@wayne3602 The current support for the Fever API is only in its initial stage, and I will submit an update soon.

**Comment by wayne3602** [comment]
Thanks!😘

**Comment by Ashinch** [comment]
Checking #406 or waiting for 0.9.9

**Comment by mbestavros** [comment]
Just seeing this now - the `0.9.8` release was cut right before my fix in #406 got merged, so `0.9.9` might help once it gets released. I've been using a version of Read You that has my fix, and the Fever API integration feels pretty complete.

**Comment by Ashinch** [comment]
@mbestavros Version 0.9.9 will be available in October

**Comment by dotvhs** [comment]
> If you want to try an updated APK with the latest fixes, you can try unzipping the artifacts from a recent Github Actions build ([here](https://github.com/Ashinch/ReadYou/actions/runs/6282440777), for example) and installing the resulting APK.

That version you linked keeps throwing me "Not valid credentials", while the same credentials work just fine with current 0.9.8.

**Comment by Ashinch** [comment]
Hi, @wayner6 

Was your problem solved in version `0.9.11+`?

**Comment by wayner6** [comment]
@Ashinch No,the problem was solved,Thanks!
