### ISSUE TITLE
UX Feature Requests: Sliding animations, Edit bottom bar, "Coming Soon" alert

### ISSUE THREAD

**Issue by candideu** [Ashinch/ReadYou#360]
**1. Environment**

-   Device: Pixel 5a
-   OS: Android 13
-   APP: 0.9.7

**2. Describe the feature request**
Hello! First, I would like to thank you for creating this app. It's one of the most beautifully designed and feature-rich RSS apps I've tested so far! I love the amount of customizations available, appreciate that you're showing us [your progress](https://github.com/users/Ashinch/projects/2), and I can't wait for the read aloud function!

I just wanted to suggest a few features. Please let me know if these should be separate Issues:

# Sliding animation for list of feeds to posts versus pop up

Currently, when you navigate from your list of feed sources to your list of articles, the screen jumps with a sort of 'pop-up'/'slight zoom-in' animation, which feels jarring:

![](https://i.imgur.com/EDY9rdL.gif)

In comparison, [Feeder](https://gitlab.com/spacecowboy/Feeder), another Material-based RSS reader, uses a slide in/slide out animation which feels a lot more fluid:

![](https://i.imgur.com/8aKzEr1.gif)

# Edit bottom bar
I'd like to have the ability to edit the order of the icons at the bottom. I'd like to move the "Starred" folder to the far-right.
![image](https://user-images.githubusercontent.com/55474996/223816112-e009c472-13bf-41b4-93d3-5c7fb464847a.png)

# "Coming soon" alert for greyed out features
It would be helpful for greyed out features, like the Read Aloud, to have a little alert saying "Coming Soon", so that users don't think that the feature doesn't work for them.

![image](https://user-images.githubusercontent.com/55474996/223823411-9014b380-d061-4c54-ae0e-3c9a2e0fe07e.png)

**Comment by Ashinch** [comment]
#540
