### ISSUE TITLE
Not valid credentials

### ISSUE THREAD

**Issue by yaotutu** [Ashinch/ReadYou#365]
**1. Environment**

-   Device: [xiaomi 12s]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the bug**
the app be download by fdroid.
I am using self-host service like freshrss,
   when login by fever-api, have a problem ,"Not valid credentials".  the url and account is right because i test the url and account on  reeder app .
_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by yaotutu** [comment]
I have used the public network mapping service and modified the baseurl in the Freshrss configuration file. After that, I can log in normally. Before modifying this, the reeder on ios can be used normally, but readyou cannot log in normally. After modification, both readyou and reeder can be used normally.

**Comment by Ashinch** [comment]
@yaotutu Hi, could you please let me know what are the differences between the new baseUrl and the old baseUrl ?
