### ISSUE TITLE
Open in browser

### ISSUE THREAD

**Issue by Donkey-Doug** [Ashinch/ReadYou#37]
Make ot possible to open the articles in the browser. Also make it possible to have "open in browser" as default. Perhaps also allow per feed custom settings (for example, open youtube video in youtube app, but read articles in readyou).

**Comment by Ashinch** [comment]
Currently you can open in browser by clicking on the title of the article, just like Reeder.

Consider add options for  default.

**Comment by Coderdude112** [comment]
I think it would be nice to be able to automatically open an article in the browser without having to click on the title. There are just some feeds that are exponentially better in the browser

**Comment by Frivolous2** [comment]
Opening in a custom tab would be really useful as well - all the benefits of browser rendering the page, but without having to close tabs once finished reading the article.

**Comment by Ashinch** [comment]
Done

**Comment by jayc331** [comment]
@Ashinch I know this is 2 years later but I cannot find custom tabs in the app. Could you help me find them, or otherwise add the feature?
