### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by changho3995** [Ashinch/ReadYou#372]
**1. Environment**

-   Device: GalaxyS10
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the feature request**

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

If you touch the image, you can see only the image in a larger size, and it would be nice if you could save it as well.

**Comment by Ashinch** [comment]
#545
