### ISSUE TITLE
Support for Right-to-left text layout

### ISSUE THREAD

**Issue by Ehab-d** [Ashinch/ReadYou#376]
ReadYou should be able to properly display articles written in Arabic, which is a right-to-left language. Currently, the app only supports left-to-right languages and the display of Arabic articles is compromised.

It would be great if ReadYou can add support for Arabic text so that users can fully enjoy reading Arabic articles without facing any formatting or display errors.

Here is an Arabic tech blog RSS feed for testing:
http://feeds.feedburner.com/computer-wd

**Comment by JunkFood02** [comment]
Duplicate of #86
