### ISSUE TITLE
Fever: Cannot fetch unread articles

### ISSUE THREAD

**Issue by steakscience** [Ashinch/ReadYou#379]
**1. Environment**

-   Device: Pixel 6a
-   OS: Android 13
-   APP: 0.9.7

**2. Describe the bug**

Cannot fetch unread articles using Fever but can fetch all or starred just fine

![Screenshot_20230407-071154](https://user-images.githubusercontent.com/2727095/230547365-faabd74d-86c9-41a0-867f-6c153e7b2daa.png)

**Comment by ynuwenhof** [comment]
Hey,

I just started experiencing the same bug after reaching a total article count of 750, after purging all the read articles from FreshRSS and refreshing the feed from the app, everything worked fine again.

FYI, I'm using a self-hosted instance of FreshRSS via the Fever API on version 0.9.7.

**Comment by ynuwenhof** [comment]
As expected, this "fix" was only temporary, and the bug returned.

I compiled and ran ReadYou myself to check the logs, the error originated from [Readability4J](https://github.com/dankito/Readability4J) when trying to [parse the HTML for a short description](https://github.com/Ashinch/ReadYou/blob/b6ff8dfafa5c9fd48b174ee17c37b90a9fd3f1c8/app/src/main/java/me/ash/reader/data/repository/FeverRssRepository.kt#L151).

You can find the line responsible for the exception [here](https://github.com/dankito/Readability4J/blob/170d052e99db58ecac85a77cdaa63ac8253be1fd/src/main/kotlin/net/dankito/readability4j/processor/ArticleGrabber.kt#L1118).

Unfortunately, the [Readability4J](https://github.com/dankito/Readability4J) project seems pretty dead, which means we probably can't expect a fix from the developer.

In my instance, the [Security Affairs](https://securityaffairs.com/) articles caused this error.

**Comment by steakscience** [comment]
Long-term, this app should switch away to using something not deprecated

**Comment by Ashinch** [comment]
#512
