### ISSUE TITLE
Archive and unread issue 

### ISSUE THREAD

**Issue by scottbetza** [Ashinch/ReadYou#383]
**1. Environment**

-   Device: [Pixel 5a[
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the bug**

After clicking read all on unread tab, a bunch of items come back unread again that were read. Im using synch  every 15 minutes

When setting keep archived articles for 1 day, the app still displays articles older than 1 day old. Some go back to 2019 for me.

These two items seem related. No way to delete archived items too it seems.

**Comment by mbestavros** [comment]
@scottbetza I think I may be able to reproduce your bug.

Do you use Read You with a Fever API endpoint? If so, which RSS application do you connect to?

**Comment by scottbetza** [comment]
I've since gotten a new phone and moved on to another app. But if I recall, I used some of the below.

https://feeds.arstechnica.com/arstechnica/index
https://rss.stephenslab.top/feed/2731.xml
https://www.reddit.com/r/hardwareswap/new/.rss?sort=new
https://www.ebay.com/sch/i.html?_nkw=iphone&_rss=1&rt=nc

**Comment by mbestavros** [comment]
Thanks! I just filled out a [separate bug report](https://github.com/Ashinch/ReadYou/issues/398) with a little more detail. I think it'd qualify as an extension of this one, so I also linked yours. Let me know if it makes sense to you.

I'm also drafting a PR for the associated fix.
