### ISSUE TITLE
本地导入OPML文件没有生效

### ISSUE THREAD

**Issue by HiMenma** [Ashinch/ReadYou#393]
**1. Environment**

-   Device: [OnePlus 9R]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the bug**
本地导入OPML文件没有生效，订阅信息没有刷新；已尝试重试和重新启动app。

**Comment by HiMenma** [comment]
> 遇到了同样问题，tinytinyrss导出的opml，没法导入。

我也是tinytinyrss导出的opml

**Comment by Ashinch** [comment]
@HiMenma 等待下一个 release

**Comment by HiMenma** [comment]
> @HiMenma 等待下一个 release

感谢，已成功导入。

**Comment by kwingart** [comment]
更新下，我用feedly导出的opml，成功导入了。。。我怀疑不是opml本身的问题，是导入操作的问题。
