### ISSUE TITLE
Fever API: add an option to limit the number of retrieved articles

### ISSUE THREAD

**Issue by mbestavros** [Ashinch/ReadYou#395]
Currently, the Fever API implementation in Read You fetches the entire repository of articles stored remotely. This behavior means that sync times can take a very long time, upwards of a minute, for repositories that contain thousands of articles (which isn't a particularly outlandish use case).

While there are probably more elegant solutions, it would be helpful if users were able to specify an upper limit of articles that should be fetched, and thus allowing more efficient sync times.

**Comment by mbestavros** [comment]
Okay, very interesting: I opened this issue and the corresponding pull request before I realized that the codebase already has functionality for incremental syncing (i.e. only fetching new articles). I didn't know this existed because it was added relatively recently in #363, and there hasn't been a release that includes it yet.

@Ashinch - I don't mean to one of those "update pls" types, but would you consider cutting a new release with the Fever API optimizations? The current behavior in the release build is a pretty awful experience with more than 200 or so articles, and the Fever optimizations would help significantly.

**Comment by th0mcat** [comment]
Here is an up-to-date APK that includes the latest commit from April 13th and everything before it (the Fever API fixes).  Things to note:

· **This is not an official APK from Ash**.  You are trusting that I did not inject any malicious code into the APK.  I didn't, I simply compiled the APK inside of Android Studio.  You can do this as well from your own home computer, I don't have instructions typed up on how to do it but if you Google around you should be able to learn how to do it.

· **This won't install over your existing instance of Read You.**  You will have to uninstall, then install my APK.  When Ash releases a new version, you will have to do the same thing (uninstall my APK, then install from Google Play/F-Droid/GitHub/Telegram).

[ReadYou-0.9.7-b6ff8df.zip](https://github.com/Ashinch/ReadYou/files/11465571/ReadYou-0.9.7-b6ff8df.zip)

**Comment by mbestavros** [comment]
Thanks, @th0mcat! I ended up compiling the app myself, but I'm sure others will appreciate a pre-built APK. The Fever API optimizations do indeed work wonders.

I'd still love a new official release, since the debug build feels pretty janky on my device. Plus, there are plenty of people who won't be willing or able to compile it themselves, and they should have access to these changes too.

**Comment by mbestavros** [comment]
Closing this, since the associated PR was also closed.
