### ISSUE TITLE
Publish the app on the Play Store

### ISSUE THREAD

**Issue by JohnBetaro** [Ashinch/ReadYou#397]
The title says it all, we will really appreciate publishing you app in the Play Store so it will be easy to get and benefit from auto updates.

I hope you'll consider my thoughts, and I'm sure that I'm not the only one who will ask for this.

**Comment by pabloscloud** [comment]
It's already in F-Droid so you can get autoupdates. Unnecessary imho

**Comment by Ashinch** [comment]
@JohnBetaro I have paid for the developer fee on Play Store and will launch my product after the interface is redesigned.

**Comment by pabloscloud** [comment]
> With all my respect, I wasn't asking for your opinion, I have my reasons which will be only discussed with the main developer.

I knew this, but it will just take time and money from the developer where I don't see a value. Maybe that's because I use F-Droid anyways?

**Comment by JohnBetaro** [comment]
I don't use the Play Store anymore, Obtainium is the way to go, closing this issue but feel free to reopen it if you are planning to keep it as a reference.
