### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [Ashinch/ReadYou#40]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, are you still ok with the integration of this app in F-Droid repo ?

**Comment by Ashinch** [comment]
A user open an [RFP](https://gitlab.com/fdroid/rfp/-/issues/2088) for me earlier (thanks) and I would like to be able to add it to F-Droid, so I created Fastlane.

But I don't have much time to deal with that aspect at the moment, maybe someone else can open a merge request at fdroiddata and maybe I'll take the time to deal with it, too.

**Comment by linsui** [comment]
Wow, it looks beautiful! I‘ll have a try.

**Comment by linsui** [comment]
The app is awesome! Looking forward to getting more function.

@Ashinch Could you please embed the ToS in the apk? I would say it's weird that I have to open Gitee to know that the app doesn't track me.

The app [check update on start](https://github.com/Ashinch/ReadYou/blob/f2571f133e1981ffb2ad3ed62c464f1761cc3a51/app/src/main/java/me/ash/reader/App.kt#L76) without any action. So as soon as I start it it connects to github/gitee. This doesn't make sense for F-Droid users. I'll remove these chechupdate in F-Droid build or even better you can add a flavor for F-Droid without update check.

Thanks!

**Comment by linsui** [comment]
It looks good to me. Thanks!

**Comment by licaon-kter** [comment]
@Ashinch any news on the ToS inclusion? The app appears ready to merge but it will get [AntiFeature: NonFreeNet](https://f-droid.org/docs/Build_Metadata_Reference/#AntiFeatures) if it needs an external proprietary server to show a bit of text. :(

**Comment by Ashinch** [comment]
#113 

The latest main branch already includes a built-in ToS.

**Comment by linsui** [comment]
Thanks! The MR is merged. ReadYou will be available on F-Droid in a week.

**Comment by Ashinch** [comment]
@linsui Thank you all very much for your help! ❤️

**Comment by daffydock** [comment]
It is on F-Droid. Congrats.

**Comment by linsui** [comment]
Here is the F-Droid badge:

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/me.ash.reader)
```

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/me.ash.reader)

**Comment by Ashinch** [comment]
@linsui Thank you very much, I will change the README soon.

**Comment by jcperil** [comment]
As it has been solved, you can unpin this issue.

**Comment by DerpyPlayz18** [comment]
The last three updates still aren't on f-droid, is it an f-droid issue or something else?

**Comment by licaon-kter** [comment]
0.9.10 is live already, update you index in Client (pull to refresh) :wink:

**Comment by DerpyPlayz18** [comment]
Found it. It was an issue on my end (I probably installed it from GitHub and now it is incompatible with the f-droid version so it wasn't being recommended to me), sorry.

**Comment by candideu** [comment]
Hi! Looks like the latest release hasn't reached F-droid yet

**Comment by linsui** [comment]
Hi, it will be published soon.

**Comment by xuangeyouneihan** [comment]
Hi! Looks like v0.10.0 hasn't reached F-droid yet

**Comment by Ashinch** [comment]
> Hi! Looks like v0.10.0 hasn't reached F-droid yet

Hi, @xuangeyouneihan

F-Droid release channel requires manual pushing.

Hi, @linsui 

I would like to request skipping version 0.10.0 and instead pushing the update to F-Droid after version 0.10.1 is released. There is a serious bug in version 0.10.0 that causes crashes for early users.

Thank you very much!

**Comment by linsui** [comment]
> Hi! Looks like v0.10.0 hasn't reached F-droid yet

Hi, of course, F-Droid update process takes about 3 days generally.

> I would like to request skipping version 0.10.0 and instead pushing the update to F-Droid after version 0.10.1 is released. There is a serious bug in version 0.10.0 that causes crashes for early use

No problem.

**Comment by licaon-kter** [comment]
@xuangeyouneihan 
> Hi! Looks like v0.10.0 hasn't reached F-droid yet

https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

@Ashinch 
> F-Droid release channel requires manual pushing.

fyi, the app is on "autoupdate": https://gitlab.com/fdroid/fdroiddata/-/commit/c6b69c516a9cdda5bddda8c72ad4def19690250b

**Comment by licaon-kter** [comment]
I've disabled 0.10.0 https://gitlab.com/fdroid/fdroiddata/-/commit/4d65f2e9c71f1c40d52af785f6125dfe9e58e0c9

**Comment by shuvashish76** [comment]
> https://github.com/Ashinch/ReadYou/issues/703#issuecomment-2143728161

Please do make the update checker opt-in for F-Droid & if possible remove unsplash connection. Thanks.

**Comment by licaon-kter** [comment]
@shuvashish76 added the AF: https://gitlab.com/fdroid/fdroiddata/-/commit/5377c35d1d5872ce10cd8beab9e90fb35d4c035b

**Comment by licaon-kter** [comment]
@shuvashish76 where is the updater in the UI exactly?

**Comment by Ashinch** [comment]
> @shuvashish76 where is the updater in the UI exactly?

1. The F-Droid build variant of ReadYou does not check for updates.
2. `images.unsplash.com` is used to display a placeholder image from the internet in preview styles. ReadYou will remove it and replace it with static images in future versions.
3. `besticon-demo.herokuapp.com` is used to fetch website icons for feeds. This is an API on the internet. ReadYou will remove it and replace it with a local implementation in future versions.

**Comment by licaon-kter** [comment]
@Ashinch thanks for fixing them, ping us when these are removed so we can remove the NonFreeNet flag

**Comment by Ashinch** [comment]
Hi, @linsui @licaon-kter 

Version `0.10.1` has been released.

BTW, `images.unsplash.com` has been remove.

**Comment by Ashinch** [comment]
> 3. `besticon-demo.herokuapp.com` is used to fetch website icons for feeds. This is an API on the internet. ReadYou will remove it and replace it with a local implementation in future versions.

The `besticon-demo.herokuapp.com` has been removed in #817.

**Comment by licaon-kter** [comment]
@Ashinch ping when release is tagged

**Comment by schildbach** [comment]
It seems the anti-feature on F-Droid can be removed.

**Comment by licaon-kter** [comment]
@schildbach be more explicit?

**Comment by schildbach** [comment]
> [@schildbach](https://github.com/schildbach) be more explicit?

[me.ash.reader](https://github.com/f-droid/fdroiddata/blob/master/metadata/me.ash.reader.yml#L307) has this anti-feature:

```
    antifeatures:
      NonFreeNet:
        en-US: Connects to besticon-demo.herokuapp.com
```

That's what the discussion in this issue is about.

The connection to `besticon-demo.herokuapp.com` has been removed in 2024 via 1ae5958b19d02a29e4323716ffdda2e3f87bd034 with what I believe is logic for using favicons from the individual feed sources (various open formats).

**Comment by licaon-kter** [comment]
done https://gitlab.com/fdroid/fdroiddata/-/commit/89b9c6865769b39e2c5e4211c959fb75ce416424
