### ISSUE TITLE
Fever API: already-fetched articles do not update read status when read on a different device

### ISSUE THREAD

**Issue by mbestavros** [Ashinch/ReadYou#401]
**1. Environment**

-   Device: Pixel 4a 5G
-   OS: Android 13
-   APP: 0.9.8

**2. Describe the bug**

After the API changes in #363, articles that were already fetched in a previous sync do not change read status when they are read on a different device.

For example, let's say Read You fetches these articles during an initial sync:

```
Article 1 (unread)
Article 2 (unread)
```

Let's say I read article 2. All is well, it gets marked as read on the remote repository. Now, Read You looks like this:

```
Article 1 (unread)
Article 2 (read)
```

Then, on a different device/RSS client an hour later, I see these articles:

```
Article 1 (unread)
Article 2 (read)
Article 3 (unread)
Article 4 (unread)
```

Let's say I read articles 1 and 4.

Now, let's say I go back to Read You and synchronize. I'd expect the article state to look like this:

```
Article 1 (read)
Article 2 (read)
Article 3 (unread)
Article 4 (read)
```

But instead, it looks like this:

```
Article 1 (unread)
Article 2 (read)
Article 3 (unread)
Article 4 (read)
```

This is because article 1 was _already fetched_ as part of the initial sync, and is now no longer being updated as part of the sync process.

**Comment by Ashinch** [comment]
@mbestavros 😱

**Comment by mbestavros** [comment]
@Ashinch Fortunately, I think the solution to this is relatively straightforward! The Fever API has a parameter to fetch read article IDs, and it's already [implemented](https://github.com/Ashinch/ReadYou/blob/main/app/src/main/java/me/ash/reader/data/provider/fever/FeverAPI.kt#L78) in `FeverAPI.kt`.

It seems to me like the solution is to perform that API request, then compare against the local article cache and update read status accordingly (maybe in the sync function).

While we're at it, we might as well also call [`getSavedItems`)(https://github.com/Ashinch/ReadYou/blob/main/app/src/main/java/me/ash/reader/data/provider/fever/FeverAPI.kt#L81) as well, right?

**Comment by Ashinch** [comment]
So after this, a separate request should be made for the read and unread status of the articles.

getUnreadItems()
getSavedItems()
