### ISSUE TITLE
Removed starred articles are not removed with sync

### ISSUE THREAD

**Issue by Offerel** [Ashinch/ReadYou#404]
**1. Environment**
-   Device: [Samsung Galaxy S23+]
-   OS: [Android 13]
-   APP: [0.9.8]

**2. Describe the bug**
Im using FreshRSS as a backend and setup sync via Fever API. When I unstar a starred item article in FreshRSS or an other RSS client an sync again in ReadYou, the unstarred articles are still available in ReadYou and not removed from the list.

**Comment by mbestavros** [comment]
This is an extension of #401, and should be resolved by my PR in #406. @Offerel, if you're able to try the test APK linked in the comments, let me know if it resolves the issue!

**Comment by Offerel** [comment]
Yep. The test apk solves the issue. Many thx
