### ISSUE TITLE
Local backup

### ISSUE THREAD

**Issue by Donkey-Doug** [Ashinch/ReadYou#41]
Make it possible to export and import a file (maybe csv or json) that contains all settings. This way users can easily backup the app settings. Perhaps also include the OPML in the backup file.

**Comment by Ashinch** [comment]
Because the account settings are not available yet, but for now you can temporarily export OPML files by long pressing the ReadYou text, but it embeds some properties of the feature, such as the "If notification is allowed".

**Comment by ph00lt0** [comment]
@Ashinch small req. could you add a datestamp to the filename e.g: 2022-06-07_ReadYou.opml thanks!

**Comment by Ashinch** [comment]
> @Ashinch small req. could you add a datestamp to the filename e.g: 2022-06-07_ReadYou.opml thanks!

Good suggestion!

**Comment by CyberaxAnnon** [comment]
Where can I find this? In app or within the android files?

**Comment by ph00lt0** [comment]
@CyberaxAnnon it's very hidden atm you have to hold the title of the app "Read You" on the main screen.

**Comment by ph00lt0** [comment]
Although that really is a strange beast it shouldn't matter. I think you misunderstand where to hold try this:

![signal-2022-07-08-191742](https://user-images.githubusercontent.com/15004290/178048538-9684e8dd-d92f-4595-ac62-9d437816a1cb.jpeg)

**Comment by CyberaxAnnon** [comment]
Thank you so much. 
Yea it was a misunderstanding. 
Appreciate it big time. 

Now if only a back up of stared items and a total transfer was available.

**Comment by candideu** [comment]
Hi, this doesn't seem to work for me. It only prompts me to switch. Where is the export?

![image](https://user-images.githubusercontent.com/55474996/223893893-6761900c-3c98-41a6-a84d-5f0cccda203d.png)

**Comment by candideu** [comment]
Nevermind, found it under Accounts...

![image](https://user-images.githubusercontent.com/55474996/223894489-d8980c96-56fc-4fb3-adeb-c7e1230452de.png)
