### ISSUE TITLE
Offering swipes gestures and extraction of the source content

### ISSUE THREAD

**Issue by ElarabyMD** [Ashinch/ReadYou#413]
**1. Environment**

-   Device: [Samsung A72 4G]
-   OS: [Android 13]

**2. Describe the feature request**
can you offer option to go to the next article by swiping upward like TikTok instead of pressing lower tiny arrow
or offering swipes gestures in general
-----
also extraction the source content is not the best thing compared to telegram bots like https://t.me/rss2tg_bot for example or https://t.me/AximoBot it will be great if included something that allow us to get feed from social media like twitter or facebook I know it is a hard thing but it will soo useful
------
_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by sbellon** [comment]
Also, I would like to add, the opposite gesture to go one article back would be very welcome. Sometimes I advanced too fast, realizing a fraction of a second later that the previous article perhaps was of interest still and want to go back.

**Comment by wallypg** [comment]
I agree that swiping up and down on opened articles to go back and forth would improve the experience a lot.

**Comment by Ashinch** [comment]
Done
