### ISSUE TITLE
好像这个最近发布的0.9.8版本，fever接口用不了，同步不了文章

### ISSUE THREAD

**Issue by kevinwenyu** [Ashinch/ReadYou#416]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the bug**

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by Ashinch** [comment]
检查 #365，或提供更多信息

**Comment by kevinwenyu** [comment]
非常感谢，中间休息了大半年，好害怕你不更新这个软件了。知道你更新了，赶紧又下载下来，感觉还是这个软件靠谱。
