### ISSUE TITLE
建议黑暗模式的纯黑色而不是灰色

### ISSUE THREAD

**Issue by suimajian** [Ashinch/ReadYou#420]
**1. Environment**

-   Device: [Redmi 220101316C]
-   OS: [Android 12]
-   APP: [0.9.8]

**2. Describe the feature request**

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by Ashinch** [comment]
深色模式里面有 amoled 设置
