### ISSUE TITLE
Notifications doesn't work anymore since last update

### ISSUE THREAD

**Issue by paxter** [Ashinch/ReadYou#423]
**1. Environment**

-   Device: Fairphone 4
-   OS: Android 13
-   APP: [0.9.8]

**2. Describe the bug**

As title states. Since last update via F-Droid notifications on new feed elements doesn't work anymore. In app notification settings, notifications are disabled and it's not possible to re-enable.

**Comment by pinoholo** [comment]
I'm on a13 and faced with the same problem. Maybe because app do not ask for Notification Permission for Opt-In Notifications?

**Comment by br0gio** [comment]
I also don't have any notifications, It's not even available in the app permissions

**Comment by BhaturaGuy** [comment]
No notifications here
