### ISSUE TITLE
Mastodon Feeds Null Object Reference

### ISSUE THREAD

**Issue by gaussandhisgun** [Ashinch/ReadYou#427]
**1. Environment**

-   Device: [Redmi Note 9S]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the bug**

Speaking of Mastodon feeds (and cats in my news). If I try to add something like, say, https://wetdry.world/tags/catsofmastodon.rss into my Read You, i get an error stating that:

`Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference`

**Comment by billwieboldt** [comment]
Mastodon feeds appear to have been fixed in v0.9.12

**Comment by Ashinch** [comment]
#532
