### ISSUE TITLE
RSS Not work

### ISSUE THREAD

**Issue by TeaqariaWTF** [Ashinch/ReadYou#43]
**1. Environment**

-   Device: PocoX3 
-   OS: [Android 12.1]
-   APP: [0.7.7]

**2. Describe the bug**

(Want you've done some research before now)
I don't know if I'm making a mistake, but none of my RSS links are working

![Screenshot_20220505-010639_Read You](https://user-images.githubusercontent.com/90970076/166833631-c09622e2-b0eb-45f3-be92-ccd72514396e.png)

**Comment by TeaqariaWTF** [comment]
![Screenshot_20220505-011144_Read You](https://user-images.githubusercontent.com/90970076/166834008-c3218c89-a37c-465e-a3b6-974d099cff26.png)

**Comment by Ashinch** [comment]
Please add this link to #13 and I will fix them as soon as possible, they are all basically caused by the same reason.
