### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by 314resqi** [Ashinch/ReadYou#44]
**1. Environment**

-   Device: Samsung Galaxy M20
-   OS: Android 12.1
-   APP: 0.7.7

**2. Describe the feature request**

Hi, would you add option to the Material You settings which would follow system theme ?

I am using custom ROM with basic Monet customizer integrated in and I am using it to override material you color. 
And since your app has it's own material you "management", system material you doesn't propagate.
Thanks

(Want you've done some research before now)

Other apps with Material You just follow system theme and don't manage it themselves.

**Comment by Ashinch** [comment]
The color palette provided by the system is too few, most of the colors are not public, the first color palette in ReadYou follows the system color, you can select the first color palette in ReadYou settings.

**Comment by Ashinch** [comment]
I forgot to tell you, with your current special case: 
You can set the same color values as your Monet customizer in `ReadYou APP` -> `Settings` -> `Color & Style` -> `Basic Colors` -> `Last Palette`.
