### ISSUE TITLE
Custom Categories for Favorite/Saved 

### ISSUE THREAD

**Issue by ArtexJay** [Ashinch/ReadYou#442]
**1. Environment**

-   Device: Xiaomi 9t pro
-   OS: Android 11
-   APP: [0.9.8]

**2. Describe the feature request**
Add the option to add custom tags to favorited/Saved articles. So that one may be able to organize the favorite section.

**Comment by zabir128** [comment]
yes 👍

**Comment by Ashinch** [comment]
#546
