### ISSUE TITLE
Import / Export Settings

### ISSUE THREAD

**Issue by zszabo2000** [Ashinch/ReadYou#443]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the feature request**

Please add the ability to export app settings and, more importantly, locally stored RSS subscriptions. I noticed that this app can connect to services like Feedly, but I for one use it predominantly because it allows for the creation of a local list of subscriptions, i.e. doesn't require a separate account with any third party service. For this to be fully functional, the ability to import a configuration is necessary. Thank you for your consideration.

**Comment by zerobun** [comment]
Is there any import option too?
And the export, AFAIK it doesn't include settings of the app etc?
