### ISSUE TITLE
RSS feed is not working

### ISSUE THREAD

**Issue by RovingFox** [Ashinch/ReadYou#446]
**1. Environment**

-   Device: [Pixel 4a 5G]
-   OS: [Android 13]
-   APP: [0.9.8]

**2. Describe the bug**

The RSS feed "https://social.network.europa.eu/@EU_Commission.rss" cannot be added. Also checked with https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsocial.network.europa.eu%2F%2540EU_Commission.rss

The error that I am receiving "Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference"

**Comment by kid1412621** [comment]
This caused by missing title in rss article, then lead to NPE: https://github.com/Ashinch/ReadYou/blob/0800e838a41d1ca39843dc07f1501255a9b2ba21/app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt#L120

In such case, Reeder takes the feed title as the article title. So what do you think? @Ashinch 

<img width="600" alt="image" src="https://github.com/Ashinch/ReadYou/assets/26278054/9131363a-62bd-4c35-8dbe-289a68bbde88">

**Comment by Ashinch** [comment]
> This caused by missing title in rss article, then lead to NPE:
> 
> https://github.com/Ashinch/ReadYou/blob/0800e838a41d1ca39843dc07f1501255a9b2ba21/app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt#L120
> 
> In such case, Reeder takes the feed title as the article title. So what do you think? @Ashinch
> 
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/26278054/296764786-9131363a-62bd-4c35-8dbe-289a68bbde88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjQ4NTEsIm5iZiI6MTcwNTMyNDU1MSwicGF0aCI6Ii8yNjI3ODA1NC8yOTY3NjQ3ODYtOTEzMTM2M2EtNjJiZC00YzM1LThkYmUtMjg5YTY4YmJkZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEzMTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxY2M1YThlOTg2Mzk3ZGRjZmM3NjQ3NzVhZjU2N2VkYmNmNDE0ZjlmZDViNThhODU4MWI3ZGJlMTIyNjBlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hlnbrA8eTg33_KjQkXcXRdifsk-UyRPaSsgYl5VZ3H8">

@kid1412621 

Oh, thanks for helping me figure it out. Yeah, we should be on the same page as Reeder.
