### ISSUE TITLE
Starred Tab has "Unread" label, Unread tab has "Starred" label

### ISSUE THREAD

**Issue by betsythefc** [Ashinch/ReadYou#45]
**1. Environment**

-   Device: Galaxy Z Flip 3 5G
-   OS: Android 12
-   APP: 0.7.6

**2. Describe the bug**

![2022-05-04 Read You, Starred Tab, Unread Label, Redacted, Annotated](https://user-images.githubusercontent.com/15450365/166842148-c0c3589e-d268-45d8-8c83-dbccdee1f109.jpg)
![2022-05-04 Read You, Unread Tab, Starred Label, Redacted, Annotated](https://user-images.githubusercontent.com/15450365/166842149-d49ac42e-471a-47c2-aabd-12d8caac3512.jpg)

Screen one should say:

> Starred
> 0 Starred Items

Screen two should say:

> Unread
> 18 Unread Items

**Comment by Ashinch** [comment]
Plz update to 0.7.7.

**Comment by Ashinch** [comment]
#26
