### ISSUE TITLE
Rss feed not working for mastodon

### ISSUE THREAD

**Issue by ghost** [Ashinch/ReadYou#469]
Environment

-   Device: [Nokia C21 plus]
-   OS: [Android 11 Go edition]
-   APP: [0.9.8]

Rss feeds of mastodon like http://floss.social/@fdroidorg.rss cant be added it take a lot of time and then give error that :-
Attempt to invoke virtual method 'java.lang.String java.lang.String.toString().

This not issue with other readers so not an issue with feed probably a bug in app.

**Comment by kid1412621** [comment]
duplicated with https://github.com/Ashinch/ReadYou/issues/446
