### ISSUE TITLE
Scrolling is broken with "Remove animations" enabled

### ISSUE THREAD

**Issue by life00** [Ashinch/ReadYou#479]
**1. Environment**

-   Device: [Pixel 6a]
-   OS: [Android 14]
-   APP: [0.9.8]

**2. Describe the bug**

I prefer having `Settings > Accessibility > Color and motion > Remove animations` option turned on, however in the whole ReadYou app scrolling becomes broken with it enabled. 

By *broken* I mean that scrolling becomes sort of jumping. Without scrolling animations. This happens specifically when you scroll and lift your finger. In other Material You apps like [Obtanium](https://github.com/ImranR98/Obtainium) and [LibreTube](https://github.com/libre-tube/LibreTube) there is no such issue, so its ReadYou specific.

It is not critical, but very annoying for me and probably others who disable animations. It is likely very easy to reproduce on any device and android version.

**Comment by C-O-D** [comment]
I would really like to have smooth scrolling without having to switch on my animation. I don't have any other app on the phone that wouldn't be able to scroll smoothly with animations disabled and I don't want to have to enable my system-wide animations just for this app - it's actually a knockout factor.

**Comment by C-O-D** [comment]
> @C-O-D Do you have any other Compose apps on your device? I think this is Compose‘s problem.

Can't tell you, I'm no developer...

**Comment by JunkFood02** [comment]
@foxjaw Thanks! Just verified with my own build, the issue should be addressed after updating Compose version of the app, i.e after #502 getting merged

**Comment by JunkFood02** [comment]
https://github.com/Ashinch/ReadYou/assets/69683722/a8f34a6a-8207-4896-b338-55f5fdce2f5a

**Comment by C-O-D** [comment]
Thanks to all for saving burdens and fixing issues!

**Comment by JunkFood02** [comment]
> Don't you know that JC is still in development progress & not flushed out yet ? Not just this, but there are a lot of other issues in jc that don't follow setting modifications of android ecosystem, the most problematic issue being this.
> 
> You've coded your project in kotlin. Could've used kotlin template itself.
>
> Blame jetpack compose, & the dev for using it.

Just to clarify, admittedly Jetpack Compose is a relatively new framework under development with many compatibility issues and missing features. But it also greatly reduces the difficulty of writing and maintaining a "good" UI interface, compared to previous XML-based view system. It can be said that without this framework this app won't be existing. At the same time, if no one is willing to use a new framework, then there is no way to improve it or to develop new features for it.

Read You is an **open source project**, not a commercial product, without any "guarantee" or "warranty" in functionality and welcome all contributors to participate, such as bug reports, feature requests or direct code contributions. I don't believe that **blaming someone or a framework** is a constructive way to help improve this app

**Comment by h0m3** [comment]
I figured that if you have Developer Mode enabled on your phone (you can easily turn on any android phone) you can disable "Remove Animations" (on galaxy is "Reduce Animations" for some reason) and if you go to Developer Options you can selective turn on or off animations. On my phone you only need "Animator Duration Scale" on to properly work, all other animations are off. And it also works if you set this specific animation to 0.5x which makes the required animations faster. Its not the perfect solution but its better than leaving animations on.

Device: Samsung Galaxy S23
OS: Android 14
App Version: 0.9.12

**Comment by C-O-D** [comment]
I'm not going to hire these disgusting animations for a single app, sorry

**Comment by JunkFood02** [comment]
This issue is already resolved in recent commits which will be included in v0.10
