### ISSUE TITLE
[Bug] [Weblate] Locked translation

### ISSUE THREAD

**Issue by sebastien46** [Ashinch/ReadYou#483]
**1. Environment**

-   Device: Pixel 7
-   OS: Android 14 (GrapheneOS)
-   APP: 0.9.8

**2. Describe the bug**

Translating the app in Weblate is currently [locked](https://hosted.weblate.org/projects/readyou/android-strings/#alerts).
Apparently, this is due to a merge error from the serbian translation:
```error: could not apply 9931b53... Translated using Weblate (Serbian)```
I want to contribute to the French translation of this app because it's awesome, but sadly can't because of this.

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by Ashinch** [comment]
Thanks for the heads up, earlier Weblate got messed up for some unknown reasons and now I've reset it to the main branch of the repository.
