### ISSUE TITLE
我正在看作者大佬的源代码，就是不知道布局文件在哪里修改，想要把原有往下滑的布局改成瀑布流风格，请怎么布局文件在哪里？请指出来一下。

### ISSUE THREAD

**Issue by jjjjbow** [Ashinch/ReadYou#491]
![屏幕截图 2023-11-19 230110](https://github.com/Ashinch/ReadYou/assets/80522532/3e7b74be-a515-4ac7-872e-de75aa18b29b)
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the feature request**

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by Moderpach** [comment]
Read you 是用Jetpack compose 写的，ui布局在kotlin源码里

**Comment by Ashinch** [comment]
e.g. https://developer.android.com/jetpack/compose
