### ISSUE TITLE
Fever API won't remove items read from other devices

### ISSUE THREAD

**Issue by kid1412621** [Ashinch/ReadYou#495]
**1. Environment**

-   Device: [Pixel 5]
-   OS: [Android 14]
-   APP: [0.9.8]

**2. Describe the bug**

I'm using self hosted miniflux with Fever API. After I've read some articles from devices, the Read You won't sync read items and reduce unread count.

**Comment by mbestavros** [comment]
@kid1412621 I proposed and @Ashinch merged a pull request that fixed this and enables cross-device sync - unfortunately, it landed right after the 0.9.8 release was cut, so if that's the version you're using, you won't see it. I've been using a version compiled with my fix with Miniflux, and it's great.

@Ashinch IMO, it's beyond time to cut a `0.9.9` release. There are lots of improvements that users like @kid1412621 are missing out on because `0.9.8` is so old.

If it's too much of a burden, I'd be happy to help manage releases somehow.

**Comment by hahuo** [comment]
支持楼上 @Ashinch 什么随缘？做人一点不真实！不想做，就直说。不想做就把项目交出去，给想做的人去做，给愿意用爱发电的人去做。别tm站着茅坑不拉屎！

**Comment by JunkFood02** [comment]
@hahuo If you can't even learn how to compile the app on your own, please at least be respectful to selfless open source contributors

**Comment by Ashinch** [comment]
> @kid1412621 I proposed and @Ashinch merged a [pull request](https://github.com/Ashinch/ReadYou/pull/406) that fixed this and enables cross-device sync - unfortunately, it landed right after the `0.9.8` release was cut, so if that's the version you're using, you won't see it. I've been using a version compiled with my fix with Miniflux, and it's great.
> 
> @Ashinch IMO, it's beyond time to cut a `0.9.9` release. There are lots of improvements that users like @kid1412621 are missing out on because `0.9.8` is so old.
> 
> If it's too much of a burden, I'd be happy to help manage releases somehow.

When I don't have enough free time, I deeply appreciate everyone coming together to contribute to this project. 

@mbestavros You will be added to the list of collaborators for the project, granting you some permissions to manage the project's release plans.

---

As for the offensive remarks towards the open-source community by user @hahuo  they have been banned from this project.

> [hahuo](https://github.com/hahuo) commented [43 minutes ago](https://github.com/Ashinch/ReadYou/issues/495#issuecomment-1880319635)
支持楼上 @Ashinch 什么随缘？做人一点不真实！不想做，就直说。不想做就把项目交出去，给想做的人去做，给愿意用爱发电的人去做。别tm站着茅坑不拉屎！

**Comment by 21gffdgf** [comment]
> > @kid1412621 I proposed and @Ashinch merged a [pull request](https://github.com/Ashinch/ReadYou/pull/406) that fixed this and enables cross-device sync - unfortunately, it landed right after the `0.9.8` release was cut, so if that's the version you're using, you won't see it. I've been using a version compiled with my fix with Miniflux, and it's great.
> > @Ashinch IMO, it's beyond time to cut a `0.9.9` release. There are lots of improvements that users like @kid1412621 are missing out on because `0.9.8` is so old.
> > If it's too much of a burden, I'd be happy to help manage releases somehow.
> 
> When I don't have enough free time, I deeply appreciate everyone coming together to contribute to this project.
> 
> @mbestavros @JunkFood02 will be added to the list of collaborators for the project, granting you some permissions to manage the project's release plans.
> 
> As for the offensive remarks towards the open-source community by user @hahuo they have been banned from this project.
> 
![droplet_7a63f349](https://github.com/Ashinch/ReadYou/assets/155341691/eb29b3ee-127e-4d19-b911-36c6aea13285)

**Comment by kid1412621** [comment]
hey @mbestavros, nicely done! I've checked the issue by myself but tested with the latest code. However unable to reproduce anymore with latest build. 😂 Your answer solved my problem. Thanks.

btw @Ashinch, may I know how the apk is packaged currently? Since I've noticed a [UI(LazyColumn) lagging issue which caused by debug mode](https://stackoverflow.com/a/70596559/8140523).

**Comment by JunkFood02** [comment]
>  how the apk is packaged currently? Since I've noticed a [UI(LazyColumn) lagging issue which caused by debug mode](https://stackoverflow.com/a/70596559/8140523).

Apks should be all built under release mode according to the Build section of the README

Afaik, we might see a significant improvement on performance after updating the Compose dependencies. The current version for Compose is 1.2.0, while the current latest stable release is 1.5.4. Compose team worked hard for improving performance this year. 

I'l take a look at this when I have time

**Comment by kid1412621** [comment]
> >  how the apk is packaged currently? Since I've noticed a [UI(LazyColumn) lagging issue which caused by debug mode](https://stackoverflow.com/a/70596559/8140523).
> 
> Apks should be all built under release mode according to the Build section of the README
> 
> Afaik, we might see a significant improvement on performance after updating the Compose dependencies. The current version for Compose is 1.2.0, while the current latest stable release is 1.5.4. Compose team worked hard for improving performance this year. 
> 
> I'l take a look at this when I have time

Tkx for the info. Speaking of compose version, maybe we can use the compose-bom later on.

**Comment by mbestavros** [comment]
@Ashinch @JunkFood02 Awesome, I'm happy to help!

We should perhaps discuss protocols for release decisions, now that we have three people capable of doing it. I'll create a discussion for that.

**Comment by Ashinch** [comment]
The Fever API does not supported remove remote items, wait for newer API integrations than this XD
