### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by EvanZhangcarpe** [Ashinch/ReadYou#499]
**1. Environment**

-   Device: [redmi 10 pro]
-   OS: [Android 13]
-   APP: [0.9.6]

**2. Describe the feature request**

It is about the text setting in reading page setting， lease add line spacing settings.
Chinese article can be read comfortably when letter spacing is increased, but when reading English articles, the whole page becomes weird.

**Comment by Ashinch** [comment]
#620
