### ISSUE TITLE
bug:一个feed收到了别的feed的消息

### ISSUE THREAD

**Issue by aoout** [Ashinch/ReadYou#5]
![Screenshot_20220421_134449_me ash reader](https://user-images.githubusercontent.com/60838705/164382759-f21ca18d-de1a-495e-a84f-aca1b6c216f5.jpg)

如图所示。

如果点击标题，软件就会闪退。

**Comment by Ashinch** [comment]
请问是否使用的是CI构建的版本，CI版本有这个问题，还在开发中。正式发布的版本目前没有收到相关反馈。

**Comment by aoout** [comment]
抱歉，是的。请关闭问题吧。
