### ISSUE TITLE
Cut release 0.9.9

### ISSUE THREAD

**Issue by mbestavros** [Ashinch/ReadYou#500]
I think we should cut a new `0.9.9` release. It's been the better part of a year since `0.9.8` and several significant improvements have not been pushed to users yet, including:

- Proper cross-device sync for Fever API users (resulting in issues like https://github.com/Ashinch/ReadYou/issues/495)
- Favicon support
- Swipe to mark read

I'd like to cut a new release to get these features out to people. @Ashinch @JunkFood02 Let me know if you agree.

**Comment by Ashinch** [comment]
Yes, I think many users are looking forward to this new version. 😘
