### ISSUE TITLE
version 0.9.10 fever crashes with error decodeByteArray must not be null

### ISSUE THREAD

**Issue by SoiledBrush** [Ashinch/ReadYou#511]
-   OS: [Android 13]
-   APP: [0.9.10]

decodeByteArray(imageBytes, 0, imageBytes.size) must not be null error appears after syncing fever account. And app gets unresponsive.
[]()![Screenshot_20240110-133657.png](https://github.com/Ashinch/ReadYou/assets/43366389/90291949-b02c-4100-bf58-3d621956dc1b)

**Comment by kid1412621** [comment]
> #496
> 
> @kid1412621 
> 
> There seems to be some omissions in the handling of base64 here.

Right, I noticed as well. Let me fix later today.

**Comment by kid1412621** [comment]
Found the root cause, some of the icons are SVG other than raster image.  I'll fix it ASAP.

**Comment by mbestavros** [comment]
@Ashinch SVG icons are likely common enough that a lot of users will be affected by this bug, much like Fever breaking outright. Once @kid1412621 lands their fix, I propose one more hotfix release, then we settle down for a bit.

**Comment by kid1412621** [comment]
Hi guys, sorry for previous insufficient test. 
Now I [partly fixed the issue](https://github.com/Ashinch/ReadYou/compare/main...kid1412621:ReadYou:fix/fever-favicon). However, some SVGs with certain specs cannot draw properly, like this:
```xml
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M16 0C7.16 0 0 7.16 0 16C0 23.08 4.58 29.06 10.94 31.18C11.74 31.32 12.04 30.84 12.04 30.42C12.04 30.04 12.02 28.78 12.02 27.44C8 28.18 6.96 26.46 6.64 25.56C6.46 25.1 5.68 23.68 5 23.3C4.44 23 3.64 22.26 4.98 22.24C6.24 22.22 7.14 23.4 7.44 23.88C8.88 26.3 11.18 25.62 12.1 25.2C12.24 24.16 12.66 23.46 13.12 23.06C9.56 22.66 5.84 21.28 5.84 15.16C5.84 13.42 6.46 11.98 7.48 10.86C7.32 10.46 6.76 8.82 7.64 6.62C7.64 6.62 8.98 6.2 12.04 8.26C13.32 7.9 14.68 7.72 16.04 7.72C17.4 7.72 18.76 7.9 20.04 8.26C23.1 6.18 24.44 6.62 24.44 6.62C25.32 8.82 24.76 10.46 24.6 10.86C25.62 11.98 26.24 13.4 26.24 15.16C26.24 21.3 22.5 22.66 18.94 23.06C19.52 23.56 20.02 24.52 20.02 26.02C20.02 28.16 20 29.88 20 30.42C20 30.84 20.3 31.34 21.1 31.18C27.42 29.06 32 23.06 32 16C32 7.16 24.84 0 16 0V0Z" fill="#24292E"/>
</svg>
```
I need some time to further investigate. Feel free to point out what I've missed.

**Comment by mbestavros** [comment]
@kid1412621 Awesome work! Do you know if there are any real-world examples of SVG favicons that wouldn't be handled by your partial patch?

I'm of the mind that we should push your partial fix out ASAP (if you think it's ready as is). Like I mentioned, people **will** run into SVG favicons, and all we need for now is "good enough for a hotfix". That doesn't mean we can't improve it to be even better.

**Comment by kid1412621** [comment]
> @kid1412621 Awesome work! Do you know if there are any real-world examples of SVG favicons that wouldn't be handled by your partial patch?
> 
> I'm of the mind that we should push your partial fix out ASAP (if you think it's ready as is). Like I mentioned, people **will** run into SVG favicons, and all we need for now is "good enough for a hotfix". That doesn't mean we can't improve it to be even better later on, but if most users aren't going to encounter bad SVGs most of the time, this will still be a big improvement for most.

hi @mbestavros , I've managed to fix the improperly drawn SVG icon issue as well.
here's my [PR](https://github.com/Ashinch/ReadYou/pull/514).

**Comment by Ashinch** [comment]
@SoiledBrush 

Please try this patch:

https://github.com/Ashinch/ReadYou/actions/runs/7484948802

If it can solve this issue, we will merge it.

**Comment by SoiledBrush** [comment]
Tried it. No errors or crashes. Seems fixed👍️
