### ISSUE TITLE
Reload groups section on manual sync

### ISSUE THREAD

**Issue by nvllz** [Ashinch/ReadYou#526]
I think the groups section in Feed page should be updated automatically after triggering a manual sync.

https://github.com/Ashinch/ReadYou/assets/110673332/5c426b0b-8204-4274-a0ca-5084539ae3da

**Comment by kid1412621** [comment]
@nvllz is this happened with Fever account or Local account?

**Comment by kid1412621** [comment]
@nvllz could you help check the fix?
