### ISSUE TITLE
[MIUI]启动应用后白屏 

### ISSUE THREAD

**Issue by LuXts** [Ashinch/ReadYou#53]
**1. Environment**

-   Device: [Redmi  K40]
-   OS: [Android 12 && MIUI13]
-   APP: [0.7.7 && 0.7.8]

**2. Describe the bug**

从桌面/通知启动 App 后持续白屏，需要切换到多任务视图再进入才正常。

**Comment by LuXts** [comment]
追加：0.7.7 和 0.7.8 版本均可以在点击后正常进入，如果不点击就一直无法进入。

**Comment by Ashinch** [comment]
@LuXts 是在 APP 中点击还是多任务中点击，才能进入？

**Comment by LuXts** [comment]
> @LuXts 是在 APP 中点击还是多任务中点击，才能进入？

目前有两种进入方式：

* 在白屏状态下进入多任务视图，然后再点击APP切回去就可以进入。
* 在白屏状态下任意处滑动一下，然后就可以进入（前面说错了，点击不行）。

我把全面屏导航方式从全面屏手势改成三大金刚，还是能用方法一进入，所以第一个方法独立于第二个方法（方法一的成功不是因为进入多任务的那下滑动触发方法二）

**Comment by Ashinch** [comment]
@LuXts 已经添加的订阅源多吗？OPML文件大概多k

**Comment by LuXts** [comment]
> @LuXts 已经添加的订阅源多吗？OPML文件大概多k

只有一个订阅源，订阅源删了都能触发这个 BUG 。

**Comment by Ashinch** [comment]
@LuXts 好的，标题改一下，加上 MIUI，我收集一些相关反馈。

**Comment by JunkFood02** [comment]
这个 MIUI + Compose 的问题似乎甚至可以在其他应用中复现，只要是使用了 `NavHost` 就会出现「不进行滑动，界面元素就不会进行第一次重组」的情况

**Comment by Ashinch** [comment]
@JunkFood02 原来如此，确实有使用 NavHost

**Comment by LuXts** [comment]
@JunkFood02 
Bug 发生的时候状态栏是白色的，推测为透明状态。

![photo_2022-05-09_23-55-51](https://user-images.githubusercontent.com/49251098/167449343-40c88f17-c6c7-4cd5-a79a-e260de231b1c.jpg)

**Comment by JunkFood02** [comment]
> @JunkFood02 Bug 发生的时候状态栏是白色的，推测为透明状态。
> 
> ![photo_2022-05-09_23-55-51](https://user-images.githubusercontent.com/49251098/167449343-40c88f17-c6c7-4cd5-a79a-e260de231b1c.jpg)

🤔 有点奇怪，但无论如何这个 bug 都像是 MIUI 自身和 Compose 没有适配好的问题

**Comment by Ashinch** [comment]
@JunkFood02 之前有位小伙伴在升级到Android 12 的 MIUI 后才能正常自适应状态栏颜色。

**Comment by Ashinch** [comment]
@sooxin 在MIUI的深色模式里单独关闭ReadYou试试，我记得有人反馈过

**Comment by LuXts** [comment]
> @sooxin 在MIUI的深色模式里单独关闭ReadYou试试，我记得有人反馈过

关掉深色模式解决了，但是我的 MIUI 没有单独关闭某应用的夜间模式选项。。。。。。

**Comment by Ashinch** [comment]
@vixpr Thank you for your reminder. I will follow up.

**Comment by JunkFood02** [comment]
https://github.com/JunkFood02/Seal/commit/380ea3597ea291da8a41484028e5605242a7649d
