### ISSUE TITLE
Add screenshots to fastlane/f-droid

### ISSUE THREAD

**Issue by inson1** [Ashinch/ReadYou#548]
There arent any

**Comment by Ashinch** [comment]
This is a repetitive work. It is difficult for me to complete screenshots of all languages alone. If someone wants to add screenshots to F-Droid for their mother tongue or other languages, they can submit a pull request.

**Comment by inson1** [comment]
@Ashinch I meant in english, as its the main language, but yea this FR could be also for more languages

Anyway I have looked and you have some screenshots there in english, but I guess in bad structure?

**Comment by JunkFood02** [comment]
> Anyway I have looked and you have some screenshots there in english, but I guess in bad structure?

Yes, simply move screenshots (and relative path to them) from `/images` to `/images/phoneScreenshots` should work

https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by inson1** [comment]
yea I think you right

**Comment by Ashinch** [comment]
336519b
