### ISSUE TITLE
图片强行拉伸长图显示异常bug

### ISSUE THREAD

**Issue by bilibili2233a** [Ashinch/ReadYou#55]
原图和对比：[Screenshot_20220508_162140_me.ash.reader.jpg](https://user-images.githubusercontent.com/99982054/167287987-f45a5de1-37ad-454f-bf07-5bc49f9a9bf3.jpg)![Screenshot_20220508_162126_com.ruanmei.ithome.hos.jpg](https://user-images.githubusercontent.com/99982054/167287990-6c91c0a4-99b5-41e8-ae76-18a353a9f66b.jpg)
其他的也是一样，原图比例是16：9
[Screenshot_20220508_162246_me.ash.reader.jpg](https://user-images.githubusercontent.com/99982054/167287995-c5bd9bcd-0b29-4041-891b-85b267dd39b2.jpg)

**Comment by Ashinch** [comment]
@bilibili2233a 下版本修复
