### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by Donkey-Doug** [Ashinch/ReadYou#56]
How can users help translate the app?

**Comment by Ashinch** [comment]
What language would you like to translate?
I want to give an example.

**Comment by Donkey-Doug** [comment]
Dutch.

**Comment by Ashinch** [comment]
You can refer to the language file:

EN: [https://github.com/Ashinch/ReadYou/blob/main/app/src/main/res/values/strings.xml](https://github.com/Ashinch/ReadYou/blob/main/app/src/main/res/values/strings.xml)

zh-CN: [https://github.com/Ashinch/ReadYou/blob/main/app/src/main/res/values-zh-rCN/strings.xml](https://github.com/Ashinch/ReadYou/blob/main/app/src/main/res/values-zh-rCN/strings.xml)

Next, make a copy of the EN language file (`strings.xml`) and modify it on top of that.

Perhaps you noticed that the folders where the different language files are located are different.

For Dutch (nl-NL), it should be located: `/app/src/main/res/values-nl-rNL/strings.xml`

You can submit translated language files in any new form, such as links, Git, Telegram, etc.

This can be tricky, so I will consider using [weblate](https://weblate.org) to help users translate, you can also wait until then.

**Comment by Donkey-Doug** [comment]
I will wait for weblate. Please add instructions to the readme when weblate is done.

**Comment by oidwa8** [comment]
@Ashinch is there an ETA on weblate? I can translate French (or I'll take a look at the `strings.xml` file later)

**Comment by Ashinch** [comment]
> @Ashinch is there an ETA on weblate? I can translate French (or I'll take a look at the `strings.xml` file later)

Maybe 0.8.5, a conservative estimate is that it will take a month, may be earlier. Because the focus is not on that now.

**Comment by Ashinch** [comment]
> @Ashinch is there an ETA on weblate? I can translate French (or I'll take a look at the `strings.xml` file later)

I just read the instructions of Weblate, which requires the project to be create for three months, and now just over a month has passed XD.

You can wait until later, because updates are now so frequent that new strings are generated every week.

**Comment by DodoLeDev** [comment]
> @Ashinch is there an ETA on weblate? I can translate French (or I'll take a look at the `strings.xml` file later)

I can arrange to do the French translation!
I've checked the `strings.txt` file: 180 lines, it's not that much!

**Comment by DodoLeDev** [comment]
@Ashinch
**Just one question**: Should I send the translated file as a PR or just as an attachment of an issue ticket?

**Comment by Ashinch** [comment]
@DodoLeDev PR is best, because it allows you to keep a record of your contributions.😊

**Comment by oidwa8** [comment]
@DodoLeDev Ah, I suppose you can take care of it if you've already started. I have some strings translated but French is _technically_ my second language so I'm not sure how good it is.

**Comment by Ashinch** [comment]
@oidwa8 That's ok, if there are translation errors, others will make suggestions.

**Comment by quytttb** [comment]
Vietnamese pls

**Comment by shuvashish76** [comment]
> I just read the instructions of Weblate, which requires the project to be create for three months, and now just over a month has passed XD.
You can wait until later, because updates are now so frequent that new strings are generated every week.

@comradekingu any possibility of speed up the process?

https://hosted.weblate.org/projects/read-you/

**Comment by Zavarash** [comment]
I want to help translate the app to Brazilian Portuguese, what do I need to do?

**Comment by comradekingu** [comment]
https://hosted.weblate.org/hosting/ is also a viable option. I can help set that up :)

**Comment by chengnan049** [comment]
> I want to help translate the app to Brazilian Portuguese, what do I need to do?

Make a copy of the EN language file (strings.xml) and modify it on top of that.

Perhaps you noticed that the folders where the different language files are located are different.

For Dutch (nl-NL), it should be located: /app/src/main/res/values-nl-rNL/strings.xml

**Comment by Ashinch** [comment]
Weblate is now available: https://hosted.weblate.org/projects/readyou/

Whenever a new translation file is approved and pushed to GitHub, it will be automatically built as an APK file.

You can view a preview of the translated language version at https://github.com/Ashinch/ReadYou/actions

**Comment by JunkFood02** [comment]
@Ashinch Hosted Weblate 的 commit 量有点灌水，可以 squash 成一个
Component - Manage - Add-ons - Squash Git commits

**Comment by chengnan049** [comment]
@JunkFood02 臣附议

**Comment by Ashinch** [comment]
> @Ashinch Hosted Weblate 的 commit 量有点灌水，可以 squash 成一个 Component - Manage - Add-ons - Squash Git commits

Done.
