### ISSUE TITLE
"Mark All as Read" doesn't mark articles as read on the server

### ISSUE THREAD

**Issue by dontobi** [Ashinch/ReadYou#561]
**1. Environment**

-   Device: Pixel 8
-   OS: Android 14
-   APP: 0.9.11 (latest Actions Release)

**2. Describe the bug**

I've been using ReadYou for a few days with a FreshRSS instance that I run via Docker on my own server. With a version from yesterday I was not able to mark all articles as read. With the latest version of Actions this does not work at the moment.

**Comment by mbestavros** [comment]
Can confirm, seeing the same bug.

I'm also seeing it on the Fever API, as well, which is a regression. It was working fine before.

**Comment by dontobi** [comment]
Has the problem already been resolved? I have seen the commits 01f5f3865b9ec3337ac92c034ca6a00154b3f72d and 9b061e4631fee4531ebf73e5bd7ed567f69941e4.

**Comment by Ashinch** [comment]
@dontobi It has not been tested and may not have been fully solved.

**Comment by Ashinch** [comment]
> If you want me to test a build, please let me know.如果你想让我测试一个版本，请告诉我。

Hi, @dontobi 

I will commit the relevant fixes to the main branch in the next few days. If you want to test it, you can get the nightly build from GitHub Actions at that time.

**Comment by SoiledBrush** [comment]
Still encountering this issue on fever, latest build.

**Comment by Ashinch** [comment]
> Still encountering this issue on fever, latest build.

@SoiledBrush 

Oh, that looks bad. Please open a separate issue specifically for mark all as read via Fever API. I’ll follow up on it.
