### ISSUE TITLE
Import OPML File exported from Feeder doesn't work

### ISSUE THREAD

**Issue by tvnmguy** [Ashinch/ReadYou#564]
**1. Environment**

-   Device: Redmi note 8 pro
-   OS: MIUI 12.5 - Android 11
-   APP: 0.9.11 f-droid build

**2. Bug**

Importing feeder backup opml file doesnt work on readyou fdroid build.

**Comment by Ashinch** [comment]
Feeder added `<feeder:settings>` tag to its exported OPML file from latest version, which is not compatible with ReadYou. Please remove it and import again or wait for further compatibility fixes.

e.g.

```
<feeder:settings>
      <feeder:setting key="pref_swipe_as_read" value="ONLY_FROM_END"/>
      <feeder:setting key="pref_added_feeder_news" value="true"/>
    </feeder:settings>
```

**Comment by Ashinch** [comment]
Wait https://github.com/mdewilde/opml-parser/issues/3

**Comment by kacperwyczawski** [comment]
I still have the same problem
