### ISSUE TITLE
Titles cut off

### ISSUE THREAD

**Issue by McBaumwolle** [Ashinch/ReadYou#566]
**1. Environment**

-   Device: Pixel 8
-   OS: Android 14
-   APP: 0.9.11

**2. Describe the bug**

Titles of the RSS fees are cut off sometimes, see screenshot. 

![Screenshot_20240124-173209.png](https://github.com/Ashinch/ReadYou/assets/67203883/fd8e8bf6-56dd-4e9f-8f24-11f7d786c8ee)

**Comment by Ashinch** [comment]
It has been fixed in the recent commit.
