### ISSUE TITLE
本地看微博的时候有排版bug

### ISSUE THREAD

**Issue by sssllllyyyy** [Ashinch/ReadYou#57]
**1. Environment**

-   Device: 小米
-   OS: miui13
-   APP: 0.7.8

**2. Describe the bug**
带表情，带链接，带视频的微博就会出现排版bug
![IMG_20220508_221001](https://user-images.githubusercontent.com/105160783/167300282-2c869008-441d-43c9-9d4c-4a8f48b0c9a1.jpg)
![IMG_20220508_221029](https://user-images.githubusercontent.com/105160783/167300286-9e014ccb-ecac-40c0-b2fe-f62c60a5b648.jpg)
![IMG_20220508_221135](https://user-images.githubusercontent.com/105160783/167300292-2580b121-a927-4cba-992f-ca6bf0955754.jpg)
![IMG_20220508_221227](https://user-images.githubusercontent.com/105160783/167300294-8a87811c-0ee0-4850-af88-f79621f5e941.jpg)

(Want you've done some research before now)

**Comment by Ashinch** [comment]
下版重构阅读页面，等下版本再试试

**Comment by sssllllyyyy** [comment]
> 下版重构阅读页面，等下版本再试试

好的，希望可以像reader那样内置一个浏览器，用起来更方便点
