### ISSUE TITLE
Option for the Light and Dark Modes to Follow Android System Theme

### ISSUE THREAD

**Issue by billwieboldt** [Ashinch/ReadYou#573]
Suggesting an additional option under Color & Style Settings for the light and dark modes to follow the system theme. This would give users the ability to have dark mode automatically enabled from sunset to sunrise if that option is enabled in system settings. From what I understand, this is possible for users on Android 10, API level 29 and above.

**Comment by JunkFood02** [comment]
Just tap on `Dark theme`

**Comment by billwieboldt** [comment]
I didn't realize there were further options hidden there beyond the on/off toggle. Thanks for the quick reply and your work on this project.
