### ISSUE TITLE
Swipe actions

### ISSUE THREAD

**Issue by shuvashish76** [Ashinch/ReadYou#606]
### Describe the feature request

Read You is know for it's customization since now we've #594 ready, I'd like to suggest configuration for them. (similar to #605)

![swipe action configuration](https://github.com/Ashinch/ReadYou/assets/48226312/a28d835a-d82b-45da-996d-a11bb8f1f847)
idea from [QKSMS](https://github.com/moezbhatti/qksms).

Actions for right and left swipe
- Read/Unread
- Star/Unstar
- Share

e.g:
|  | Right swipe | Left swipe |
|--------|--------|--------|
| Read/Unread | Yes | No |
| Star/Unstar | No | Yes |
| Share | No | No |

**Comment by JunkFood02** [comment]
duplicate of #586
