### ISSUE TITLE
Weird Swipe action behaviour

### ISSUE THREAD

**Issue by shuvashish76** [Ashinch/ReadYou#607]
### Environment

-   Device: Lenovo TB-8704X
-   OS: Android 9
-   APP: 0.9.12 (23) (from latest GH action)

### Describe the bug

My swipe action setup is default one i.e. Swipe left to Toggle starred, Swipe right to Toggle read

Steps:
1. Swipe right > maked as read ✔️
2. Swipe left > star marked ✔️ but at the same time it marks it as unread ❌ now each time you perform swipe left it marks unread/read ❌
3. When the article is in both Unread & Star > swipe right > it does nothing ❌, it works only if you remove from the star.

https://github.com/Ashinch/ReadYou/assets/48226312/97d5e221-a8ce-4bd4-8efa-1a053328c71e

**Comment by JunkFood02** [comment]
#547

**Comment by shuvashish76** [comment]
Without going through the full discussion, for those who are looking for similar behavior it can be changed from Settings > Color & style > Flow page > Gray out articles > change to All read.
Thanks.
