### ISSUE TITLE
Future date articles

### ISSUE THREAD

**Issue by shuvashish76** [Ashinch/ReadYou#616]
### Describe the bug

Some sites show RSS from future dates e.g:
https://www.edweek.org/index.rss

![Screenshot_2024-02-12_15-58-34_1](https://github.com/Ashinch/ReadYou/assets/48226312/44b81feb-6f2e-4778-a387-19e9f57709c3)

Change them to the time of device synchronization to not show them on top of all other articles for a long period of time.

**Comment by ch3thanhs** [comment]
Hi @Ashinch, Can you please consider issue #98 along with this one?
