### ISSUE TITLE
关于 MD3 TopAppBar 的滚动行为

### ISSUE THREAD

**Issue by JunkFood02** [Ashinch/ReadYou#62]
[MD3设计规范](https://m3.material.io/components/top-app-bar/guidelines) 里对 Top app bars 的 scrollBehavior 做了规定，虽然看到应用里实现顶栏的做法其实是用一个无标题的顶栏外加一个 Text 组件模拟出来的，但是在原生 Android 12 的系统设置里的这个顶栏的 scrollBehavior 做得很符合设计规范，也控制好了状态栏的变色，现在在 Compose 里是目前还没有实现这个行为的方法吗？

**Comment by Ashinch** [comment]
有，但是嵌套滚动和下拉刷新有点问题，所以我暂时移除了，我研究好了会加回去的
