### ISSUE TITLE
[UI] RTL locales not working on Android 12 and below

### ISSUE THREAD

**Issue by egorikftp** [Ashinch/ReadYou#634]
**1. Environment**

-   Device: [Pixel 3a XL]
-   OS: [Android 12]
-   APP: latest dev

**2. Describe the bug**
Try to switch language to arabic and observe correct layout for a few seconds (RTL), them LTR

Demo:

https://github.com/Ashinch/ReadYou/assets/16294951/efa8263b-c922-4399-8b3f-501734cfc1c7

**Comment by JunkFood02** [comment]
Can't reproduce on my devices(all of them). Are you using a custom rom?

**Comment by egorikftp** [comment]
Build from: https://github.com/Ashinch/ReadYou/actions/runs/8131906430

No any changes in ROM, official Android

**Comment by egorikftp** [comment]
Found issue: https://issuetracker.google.com/issues/250220912
