### ISSUE TITLE
Ability to swipe to favorite an item

### ISSUE THREAD

**Issue by K4LCIFER** [Ashinch/ReadYou#637]
**1. Environment**

-   Device: Google Pixel 6 Pro
-   OS: Android 14
-   APP: 0.9.12

**2. Describe the feature request**

Currently you can swipe to mark an item as read, but it would be nice to also be able to swipe to favorite an item.

**Comment by JunkFood02** [comment]
duplicate of #606

**Comment by K4LCIFER** [comment]
Ah, my bad! Sorry about that! I'm looking forward to the feature! :smile:
