### ISSUE TITLE
读着读着就卡死

### ISSUE THREAD

**Issue by xuangeyouneihan** [Ashinch/ReadYou#641]
**1. Environment**

-   Device: Redmi K50 Pro (Rooted with Magisk 27.0), Huawei Honor 10
-   OS: Android 14, Harmony OS 3 (Android 10)
-   APP: 0.9.12

**2. Describe the bug**

如题，应用会在浏览过几篇文章后点击下一篇文章的按钮时卡死。在我的红米K50Pro上F-Droid版和Github Release版均有此问题，同样也在荣耀10上复现。相同的是软件在崩溃之前都提示Failed Requirement，不同的是红米K50Pro是在点击下一篇按钮之后卡住不动，荣耀10是闪退回桌面。虽然红米K50Pro已Root，但是无论是否将应用添加到排除列表都会崩溃。WSA上尚未发现此问题。账户是甲骨文云上搭建的FreshRss

用`adb logcat | findstr me.ash.reader > [输出路径]`在红米K50Pro上抓取的日志：[logcat.txt](https://github.com/Ashinch/ReadYou/files/14540398/logcat.txt)

https://github.com/Ashinch/ReadYou/assets/50788434/a2eab0b8-1b23-4640-a8e2-c7845ca34461

**Comment by xuangeyouneihan** [comment]
@Ashinch 你好，信息已经填完了，有时间的话麻烦看一眼，谢了

**Comment by JunkFood02** [comment]
Try installing the package from this CI artifact to see if the issue could be reprocued: https://github.com/Ashinch/ReadYou/actions/runs/8202439402

**Comment by xuangeyouneihan** [comment]
没了，我是傻逼
It works well. I'm stupid
