### ISSUE TITLE
The app is on the play sore

### ISSUE THREAD

**Issue by rudythug** [Ashinch/ReadYou#657]
Hello, 

Not sure if it's ok but your app is now on the play store : https://play.google.com/store/apps/details?id=work.mywild.feeds&hl=fr

More over the dev reuse the name "Read You" in the description and don't mention the project

**Comment by djacidfx** [comment]
The app published follows this, it has a link directly to the source repo in-app that shows it's forked from the original author so that anyone who wants to see the code, can. I wasn't expecting anyone to post something like this to advertise the app I published before I could make any changes from the original to add my own changes to it but, I have revised the description and if the original author would like me to remove it I will without any hesitation.

Here's a breakdown of forking and publishing an app under the GPL 3.0, as well as things to consider:

Fundamentals of GPL 3.0

    Derivative Works: Forking a GPL 3.0 project creates a derivative work. This means your app is bound by the terms of the GPL 3.0.
    Distribution: If you distribute your app (even for free), you must make it available under the same GPL 3.0 license.
    Source Code: You must provide the complete corresponding source code of your app to anyone who receives a copy. This code must be under the GPL 3.0 license.

Can you publish a free app?

Yes, you absolutely can. Here's what you need to do:

    Licensing: Your app must be licensed under GPL 3.0.
    Full Source Code: Anyone receiving your app needs access to the full source code under the GPL 3.0. Common ways to achieve this include:
        Including the source code directly with your app
        Providing a clear download link to the source code
        Offering to provide a physical copy of the source code upon request (you may charge a small fee for materials and shipping).
    Attribution: While not explicitly required by the GPL 3.0, it's best practice and good etiquette to:
        Clearly state your app is a derivative work of the original project.
        Provide a link to the original repository.

**Comment by alxthmpson** [comment]
@djacidfx, I'm very impressed with the icons that you've used for your apps on the Play Store.

Who was the artist? Please let me know, I need some icons for my project.

**Comment by djacidfx** [comment]
Clearly you didn't read what I said about not having time recently to really make any meaningful changes yet; I've done more than just changing some strings around. It wasn't being advertised for that very reason until it could clearly be distinguished from the original work. I could care less what you think I've done with any of my apps, that's no concern of mine, you're free to feel how you want. If the original author wants me to take the app down, I will and will delete the original code and repo, don't bother me one bit.

> Hi @djacidfx, literally neither I nor anyone else on the Internet, cares about the fact that you constantly clone, "rebrand", or simply steal open source projects as your own apps. But [your fork](https://github.com/djacidfx/ReadYou) clearly does NOT reflect the changes you've made on our app (though i believe you just replaced some strings), which indicates that you've violated the GPLv3 license

**Comment by JunkFood02** [comment]
> If the original author wants me to take the app down, I will and will delete the original code and repo.

@djacidfx Cool, I'm the author/commiter of about 40+ commit in ReadYou, and my code is licensed under GPLv3 which also appears in your branch. If you are not willing to sync your changes to your branch to comply with the GPLv3 license, please delete the entire repo, or at least all of the commits with me as the author. 😉

**Comment by alxthmpson** [comment]
@djacidfx, The only changes you are capable of making are "AI generated icons" and "find and replace" strings.

Based on the other apps in your roster it's clear that you have no intention to make any changes of your own.

"Lack of time", get real.

**Comment by alxthmpson** [comment]
@JunkFood02, He has removed the RSS reader app changed the app ID to point to a different app and claims he got $800 😂 and also "free traffic", more like 3-4 people 🤣.

Play Store -

![Play Store](https://github.com/Ashinch/ReadYou/assets/163124499/afcf5885-b8ab-44d8-ac6a-5be46bfce1f5)

GitHub -

![GitHub](https://github.com/Ashinch/ReadYou/assets/163124499/7863cbfa-f7cc-4b05-8649-953a3bf2925f)

**Comment by djacidfx** [comment]
You girls still crying over my apps?

**Comment by rudythug** [comment]
I'm glad you've made money from my issues, and then I'll continue to help you get richer.

**Comment by alxthmpson** [comment]
I think this issue can be closed, the URL leads to 404.
