### ISSUE TITLE
建议优化同步性能

### ISSUE THREAD

**Issue by matoung** [Ashinch/ReadYou#661]
**1. Environment**

-   Device: [Honor Magic 5]
-   OS: [Android 14]
-   APP: [0.9.12]

**2. Describe the feature request**

Read You使用Miniflux集成的Google Reader API/Fever API同步比较慢，其他客户端正常，是不是没有做批量同步？比如一次拉取50条，建议优化同步的性能 谢谢

**Comment by Ashinch** [comment]
- Fever API 的同步方式正如所说的 `一次拉取50条`，后续应该不会再去优化这个 API 的集成（太老了）。
- 对于 Google Reader API 的同步方式可以了解一下：[Hello Read You: 迎来 Google Reader API](https://ash7.io/blog/hello-read-you-welcome-to-google-reader-api-zh-cn/)，首次同步是会比较慢，同步速度主要取决于本地与服务器之间的数据差异，不知道你面临的是不是这个情况

**Comment by matoung** [comment]
> - Fever API 的同步方式正如所说的 `一次拉取50条`，后续应该不会再去优化这个 API 的集成（太老了）。
> - 对于 Google Reader API 的同步方式可以了解一下：[Hello Read You: 迎来 Google Reader API](https://ash7.io/blog/hello-read-you-welcome-to-google-reader-api-zh-cn/)，首次同步是会比较慢，同步速度主要取决于本地与服务器之间的数据差异，不知道你面临的是不是这个情况

相同的miniflux服务端使用agr reader或iOS的reeder首次同步也挺快的，只有不到1千条数据。
Google reader API使用read you等了很久没有同步成功，空了我再试试。

**Comment by Ashinch** [comment]
> > * Fever API 的同步方式正如所说的 `一次拉取50条`，后续应该不会再去优化这个 API 的集成（太老了）。
> > * 对于 Google Reader API 的同步方式可以了解一下：[Hello Read You: 迎来 Google Reader API](https://ash7.io/blog/hello-read-you-welcome-to-google-reader-api-zh-cn/)，首次同步是会比较慢，同步速度主要取决于本地与服务器之间的数据差异，不知道你面临的是不是这个情况
> 
> 相同的miniflux服务端使用agr reader或iOS的reeder首次同步也挺快的，只有不到1千条数据。 Google reader API使用read you等了很久没有同步成功，空了我再试试。

正常来说应该与 Reeder 差不多，可能会慢个 5～10 秒，等待你的反馈

**Comment by matoung** [comment]
> > > * Fever API 的同步方式正如所说的 `一次拉取50条`，后续应该不会再去优化这个 API 的集成（太老了）。
> > > * 对于 Google Reader API 的同步方式可以了解一下：[Hello Read You: 迎来 Google Reader API](https://ash7.io/blog/hello-read-you-welcome-to-google-reader-api-zh-cn/)，首次同步是会比较慢，同步速度主要取决于本地与服务器之间的数据差异，不知道你面临的是不是这个情况
> > 
> > 相同的miniflux服务端使用agr reader或iOS的reeder首次同步也挺快的，只有不到1千条数据。 Google reader API使用read you等了很久没有同步成功，空了我再试试。
> 
> 正常来说应该与 Reeder 差不多，可能会慢个 5～10 秒，等待你的反馈

试了下，公网下同步很慢，但局域网下Google reader API首次同步速度很快，这个问题先关了 谢谢
