### ISSUE TITLE
Text is cut off 

### ISSUE THREAD

**Issue by uniquePWD** [Ashinch/ReadYou#685]
**1. Environment**

-   Device: Pixel 8 Pro
-   OS: Android 14
-   APP:[0.9.12

**2. Describe the bug**
The text box size seems to be hardcoded and not dynamic, leading to text being cut off. 
![Screenshot_20240412-060741_1](https://github.com/Ashinch/ReadYou/assets/203217/a229fd5c-d451-41ec-bb72-9d89d173b66c)

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by aualbert** [comment]
I have the same issue with large system font.
![Screenshot_2024-05-24-18-01-33-466_me.ash.reader.jpg](https://github.com/Ashinch/ReadYou/assets/116089283/752332e5-f3f2-42dc-b42a-69ca9ad7f406)

**Comment by aualbert** [comment]
Still the case in 1.10.1
