### ISSUE TITLE
Slide left to add to wish to read

### ISSUE THREAD

**Issue by maverick74** [Ashinch/ReadYou#686]
**1. Environment**

-   Device: Xiaomi
-   OS: [Android 8]
-   APP: [0.9.6]

**2. Describe the feature request**

would be great to have a "wish to read" list (beside the actual favorites list) to which we could add articles to - that we intend to read once we have time - by just sliding left on the article on the news list. 
An alternative could be sliding left to add to favorites, but I still think two different lists would always work better, Iyam...

**Comment by maverick74** [comment]
@Ashinch do you think there's a chance for this soon or should I search another rss reader?

**Comment by maverick74** [comment]
@JunkFood02 huuummmm not sure where i can find "wish to read" list...

can you give me a tip?

**Comment by JunkFood02** [comment]
oh i missed the part of a separate list and thought it was only about swipe to star, feel free to file a new issue about it

**Comment by maverick74** [comment]
OK.

New feature request at #741

Hope it's not too much work to do it. 

It's a very useful feature (in fact i'm not using ReadYou full time yet just because of it)
