### ISSUE TITLE
When reading subscriptions under the same grouping, I would like to support infinite slide mode (after reading one, in the slide, automatically jump to the next content)

### ISSUE THREAD

**Issue by mumutoy** [Ashinch/ReadYou#7]
现在阅读的时候每次都需要左滑返回之后，才能阅读下一篇内容。

希望能添加成，顶部下拉刷新，文章底部上拉，自动跳转到下一篇内容上面，这样就可以畅快阅读了。

**Comment by Ashinch** [comment]
目前信息流页面正在重构中，后续跟进。

**Comment by pc00per** [comment]
I currently use Aggregator & sliding left & right to navigate adjacent pages is really a deal breaker. Not having such simplicity just annoys me little bit.

**Comment by mrhll** [comment]
This is a great app and the best designed but useless for me without swipe gestures to move between articles ...
