### ISSUE TITLE
Can't deselect highlighted text in reading mode.

### ISSUE THREAD

**Issue by MillionsToOne** [Ashinch/ReadYou#701]
**1. Environment**

-   Device: [Oneplus 8T]
-   OS: [LineageOS 21 based on Android 14]
-   APP: [0.9.12]

**2. Describe the bug**

When reading an article through the app, you might accidentally highlight a psrt of the text. However, most of the time you can't deselect the highlighted text, forcing you to copy the text to get rid of the copy button and highlight. It works in some articles but afaik it's random. I might upload a vieeo of what I mean if requested.

**Comment by Ashinch** [comment]
This is a bug in Compose, maybe you can try Webview Renderer #568
