### ISSUE TITLE
why does ReadYou needs these Connection to other Server

### ISSUE THREAD

**Issue by Ilav1** [Ashinch/ReadYou#703]
**1. Environment**

-   APP: [0.9.12]

**2. Describe the feature request**

I'm using net guard to control traffic of android apps.

At first I'll block all connections and open only necessary ones.

When I start ReadYou and import my feeds, the app wants to connect to my news-sites (of cause).

There are two more connections the app is trying to connect to

![Screenshot_20240523-172456_1_1](https://github.com/Ashinch/ReadYou/assets/102852954/e2c2a893-2f8f-460e-89ba-ddf2791ac77a)

The first one (besticon-demo.herojuapp.com) is to get the favicons.

Why is the app connecting to the second one follow.it?

Without accepting __**both**__ connection the news are not loading. Even when I only accept follow.it nothing happened. When I only accept the favicons link, the favicons are shown in the list but no news are loading.

News are just loading (after import my list) with both connections to 3rd parties.

When I import my list and block both connections again, everything is working fine. New news are loading and can be read in the app.

Other easy reader are able only to connect to the RSS sites I'm following.

Is it possible to get rid of these connections?

**Comment by shuvashish76** [comment]
I just installed the app, without any feeds added to it. The app connects to `api.github.com`, `images.unsplash.com`.
Does it connect to GitHub for updates checking in background? & why unsplash?

**Comment by shuvashish76** [comment]
![Screenshot_2024-06-02_09-34-24_1](https://github.com/Ashinch/ReadYou/assets/48226312/288e4e7d-0d10-4309-b2e1-657556a506f6)

I'm using the builds from GitHub [actions](https://github.com/Ashinch/ReadYou/actions)

**Comment by JunkFood02** [comment]
> The first one (besticon-demo.herojuapp.com) is to get the favicons.

https://github.com/mat/besticon

> Why is the app connecting to the second one follow.it?

Your news site uses [follow.it as a feedburner](https://follow.it/intro)

> connect to GitHub for updates checking in background? 

yes

> why unsplash?

sample image i guess?

https://github.com/Ashinch/ReadYou/blob/4b42d2ed386249f0fb964e73bb0d2a93c6c7733d/app/src/main/java/me/ash/reader/ui/page/settings/color/flow/FlowPagePreview.kt#L114

**Comment by Ilav1** [comment]
@JunkFood02 why isn't it possible to get news when beticon is blocked? I think blocking the domain only will effect the favicon images and not the news. I only get new news when both domains are allowed. 


@shuvashish76 what kind of app do you use to track the connections?

**Comment by JunkFood02** [comment]
> I think blocking the domain only will effect the favicon images and not the news. I only get new news when both domains are allowed.

no idea, maybe also disable favicon in your flow page settings?

**Comment by shuvashish76** [comment]
> > connect to GitHub for updates checking in background?
> 
> yes

Update checker enabled for F-Droid releases as well? Need [Tracking](https://f-droid.org/docs/Anti-Features/#Tracking) AF.

> > why unsplash?
> 
> sample image i guess?

Need [NonFreeNet](https://f-droid.org/docs/Anti-Features/#NonFreeNet) AF.
Both are unnecessary IMO.
@Ilav1 I'm using [RethinkDNS](https://f-droid.org/packages/com.celzero.bravedns/), alternatively you could track with [PCAPdroid](https://f-droid.org/packages/com.emanuelef.remote_capture/).
