### ISSUE TITLE
Add functionality to zoom in on images and open them in full screen

### ISSUE THREAD

**Issue by pherasymchuk** [Ashinch/ReadYou#709]
**1. Environment**

-   Device: [Xiaomi mi 9t Pro]
-   OS: [Android 14]
-   APP: [0.9.12]

**Description**:
Currently, our application lacks a feature that would allow users to zoom in on images or open them in full screen. This could be a useful feature, especially when images contain a lot of details that users might want to examine more closely.

**Steps to reproduce**:
1. Open the application
2. Navigate to the page with the image
3. Try to zoom in on the image or open it in full screen

**Expected result**:
The user should be able to zoom in on the image or open it in full screen.

**Actual result**:
Currently, there is no way to zoom in on the image or open it in full screen.

**Screenshot**:
![Screenshot_20240530-164730_Read You](https://github.com/Ashinch/ReadYou/assets/74320524/d6fbd204-3eb2-493f-8f26-ba56008a5cc0)

**Comment by JunkFood02** [comment]
Already implemented in #578, you can install preview apks from build artifacts of [github ci](https://github.com/Ashinch/ReadYou/actions?query=branch%3Amain)
