### ISSUE TITLE
Migrate to `androidx.compose.material3.pulltorefresh`

### ISSUE THREAD

**Issue by JunkFood02** [Ashinch/ReadYou#722]
Remove deprecated `accompanist-swiperefresh` from the app

Reference: https://google.github.io/accompanist/swiperefresh/

**Comment by aualbert** [comment]
It seems like `PullRefreshIndicator` is not available in `material3.pulltorefresh` but only in `material.pullrefresh`. This functionality is used in `SwipeRefresh.kt` for example.
