### ISSUE TITLE
Migrate to `androidx.compose.foundation` FlowLayouts

### ISSUE THREAD

**Issue by JunkFood02** [Ashinch/ReadYou#723]
Remove the deprecated `accompanist-flowlayout` from the app 

Reference: https://google.github.io/accompanist/flowlayout/

**Comment by aualbert** [comment]
Done as well as https://github.com/Ashinch/ReadYou/issues/721. I will issue a pull request once https://github.com/Ashinch/ReadYou/pull/744 is merged.
