### ISSUE TITLE
Opml imports doesnt sync

### ISSUE THREAD

**Issue by Gottarocket** [Ashinch/ReadYou#73]
**1. Environment**

-   Device: []
-   OS: [Android 11]
-   APP: [0.8.0]

**2. Describe the bug**
Exported opml from antennapod. Tried importing and all feed name showed up but sync ing doesnt show any article . I deleted one rss feed and copied its rss link and pasted when adding rss to read you. It worked. Rss links works but not opml import. 
(Want you've done some research before now)

**Comment by Ashinch** [comment]
@Gottarocket Finally, is the sync in progress or has the sync ended? What is the size of an OPML file?

**Comment by Gottarocket** [comment]
Syncing... doesnt show up after some time so I believe it did end and size is  7.73kb

**Comment by Ashinch** [comment]
@Gottarocket Did it not even fetch an article successfully?

**Comment by Ashinch** [comment]
@Gottarocket Did you update from 0.7.8 to 0.8.0?

**Comment by Gottarocket** [comment]
None as far as I know .

**Comment by Gottarocket** [comment]
No I downloaded this today to checkout .

**Comment by Gottarocket** [comment]
Fdroid compiled if that makes any difference

**Comment by Ashinch** [comment]
@Gottarocket If you don't mind, you can send me the OPML file for debugging. F-droid doesn't check for updates, other than that it's the same.

**Comment by Gottarocket** [comment]
https://0bin.net/paste/e6xXLcPl#NM7VHmbM1cwEYs68rdJwQMHp-pYOKYIF9trSQpIy/BY

**Comment by Ashinch** [comment]
@Gottarocket OK, I have reproduced the Issue.

**Comment by Gottarocket** [comment]
Great. Just wanted to know if its just on my end . Anyway thanks hope you can fix it soon 😄

**Comment by Donkey-Doug** [comment]
Same issue here, since 0.8.0

**Comment by Ashinch** [comment]
@Donkey-Doug The cause of the issue has been located, please use the older version until it is fixed, sorry…🥲
