### ISSUE TITLE
App doesn't work.

### ISSUE THREAD

**Issue by hozzz9487** [Ashinch/ReadYou#730]
**1. Environment**

-   Device: Zenfone 9
-   OS: Android 14
-   APP: 0.10.0

**2. Describe the bug**

I just downloaded the latest version of the app and open it, it showed me the pictures attached.
![Screenshot_20240604-132343_Read_You](https://github.com/Ashinch/ReadYou/assets/62610185/5d65461a-fa4d-4e8c-acb5-6d6a010634f4)
![Screenshot_20240604-132346_Read_You](https://github.com/Ashinch/ReadYou/assets/62610185/69271d8b-8abf-400c-8f3d-331c471162ec)

btw, I cannot copy the debug info. Full process as follows: 

https://github.com/Ashinch/ReadYou/assets/62610185/0a2000e6-8dc8-4a06-a0cb-b48d14df7909

**Comment by Ashinch** [comment]
Hi, this issue has been fixed. 

#718 

You can wait for the fixed version to be released tonight or tomorrow, or you can use the nightly build.
