### ISSUE TITLE
Gestures to improve usage efficiency

### ISSUE THREAD

**Issue by bzeiss** [Ashinch/ReadYou#739]
**1. Environment**

-   Device: [Pixel 7 pro]
-   OS: [Graphene OS]
-   APP: [0.9.6]

**2. Describe the feature request**

I use the the following terms to describe the different screens, I hope this makes sense:
- feeds list (list with all the feeds)
- feed items list (list with items in the feed)
- feed item view (content view of a single feed item)

Let's say I read a specific feed and start in the feed items list. I click a feed item to go to the feed item view. Given a phone like the Pixel 7 Pro, it's pretty uncomfortable to get back to the feed items list from the feed item view with the current item marked as read. Given the relatively big caption of the feed name "XYZ" in the feed items list, the feed items that you tap are always located in the lower two thirds of the screen when you tap a feed item. As a result, to close the current feed item, you always have to move at least one third of the screen to reach the top left "x"-control to close the current feed item. This is quite annoying when you read potentially a lot of items in a session.

Thus, I want to suggest to support gestures to improve the overall usage efficiency: 
- a swipe-left gesture in the feed item view to close the feed item and return to the feed items list 
- a swipe-left gesture in the feed items list to return to the feeds list
- a swipe-down gesture in the feed item view to mark an item as read and jump to the next item in the feed items list
- a swipe-up gesture in the feed item view to return to the last read item in the feed item view
- a swipe-down gesture in the feeds list to refresh the feeds list

**Comment by JunkFood02** [comment]
> - a swipe-down gesture in the feed item view to mark an item as read and jump to the next item in the feed items list
> - a swipe-up gesture in the feed item view to return to the last read item in the feed item view
> - a swipe-down gesture in the feeds list to refresh the feeds list

I thought these are already supported in Read You

> - a swipe-left gesture in the feed item view to close the feed item and return to the feed items list
> - a swipe-left gesture in the feed items list to return to the feeds list

You could get both for free if you're using gesture navigation instead of three-button navigation

**Comment by bzeiss** [comment]
Weird, I just updated to see whether it makes a difference and it started to work. I guess this enhancement request is indeed resolved with this.
