### ISSUE TITLE
Text Justify.

### ISSUE THREAD

**Issue by girlofparadise** [Ashinch/ReadYou#74]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]

**2. Please add option to justify text sir. Quick.

**3. Please add fast loading feature sir. Quick.

**Comment by Stealthinator16** [comment]
I have tried setting both the title and text alignment as 'justify' but the alignment remains aligned left. Tested on both 0.9.8 and 0.9.12. 

Device: OnePlus Nord 3 5g
OS: Oxygen OS 14 [Android 14.0]
App version: 0.9.8 and 0.9.12  

![WhatsApp Image 2024-02-22 at 12 59 07_950e591f](https://github.com/Ashinch/ReadYou/assets/26377083/98505568-f6a5-4541-8920-07dc323c2dc9)
![WhatsApp Image 2024-02-22 at 12 59 07_c23b23d9](https://github.com/Ashinch/ReadYou/assets/26377083/34973209-23aa-41e6-a941-ce7156afdfc0)
![WhatsApp Image 2024-02-22 at 12 59 07_ffd99b8f](https://github.com/Ashinch/ReadYou/assets/26377083/53426a20-ca2d-4134-8c7a-c0a37c4b971b)
