### ISSUE TITLE
Expand/Collapse all feed folders button + Remember preference option

### ISSUE THREAD

**Issue by Starcr0ss** [Ashinch/ReadYou#760]
**1. Environment**

-   Device: Moto G Stylus (2021)
-   OS: Android 11
-   APP: 0.10.1

**2. Describe the feature request**

The option to collapse and expand feed folders individually already exists but there is no "Expand/Collapse All" button to help quickly make a long list of feeds easily parsable. Additionally, reopening the app forgets which feed folders are expanded and collapsed. A setting to remember which folders were expanded or collapsed would make using the app more pleasant and efficient.

**Comment by aualbert** [comment]
On it!

**Comment by Nosen92** [comment]
Remebering folder collapsed/expanded state is so useful!! My Youtube folder is on the bottom, so I do a lot of collapsing to get there. This feature would be a game changer.

**Comment by JunkFood02** [comment]
Remember expanded/collapsed states + Allow reorder folders seems more practical for this use case

#54
