### ISSUE TITLE
<enclosure> tag in the item is not used

### ISSUE THREAD

**Issue by Maell1** [Ashinch/ReadYou#769]
All "enclosure" tags are not used from https://www.clubic.com/feed/news.rss  :

For example :
`<enclosure url="https://pic.clubic.com/v1/images/1882727/raw" type="image/jpeg" length="0"/>`

After the fix :
https://github.com/Ashinch/ReadYou/pull/681

https://github.com/Ashinch/ReadYou/compare/746092103f2343f24e69669dbfa9e5d88ebe49d6..b98228bd0e03ce9e08b2d50cb577c8e62f76aec3

**The regex works : https://regex101.com/r/FDuVwQ/1
Perhaps it's the attribut  length=0 or the filename with no extension...**

There are no picture with ReadYou v0.10.1.
The picture is show with Feeder.

**Comment by Ashinch** [comment]
This is because the <enclosure> of the feed is in the rss attribute, and the previous processing ignored them.
