### ISSUE TITLE
UI: use the top bar empty space to display the account/group/feed names

### ISSUE THREAD

**Issue by GLLM** [Ashinch/ReadYou#789]
Hello,

I like my screen estate to be used as much as possible in order to have as much content displayed on the screen as possible.

I would like to suggest a UI improvement.
Currently, the topbar has a lot of unused space. In the meantime, the account/group/feed titles are using a significant amount of space in the screen main part where the feed/flow content is displayed.

Do you think the topbar empty space could be used to display the account/group/feed title so that more space is dedicated to show the actual content of those sections ?

See screenshots below:

_Account name_
![Account](https://i.imgur.com/xGn0Yuo.png)
_Group name_
![Group](https://i.imgur.com/GzVc2Qf.png)
_Feed name_
![Feed](https://i.imgur.com/528cknx.png)

Thanks a lot
GLLM

Context
-   Device: [Samsung Galaxy S23+]
-   OS: [Android 14 / OneUI 6.1]
-   APP: [0.10.1]

**Comment by aualbert** [comment]
On it.

**Comment by Ashinch** [comment]
Hi, @GLLM 

This is ReadYou's main visual design, and usually we don't change it.

**Comment by GLLM** [comment]
@Ashinch thanks for your feedback
