### ISSUE TITLE
Feeds not updating

### ISSUE THREAD

**Issue by aolgeirson** [Ashinch/ReadYou#79]
**1. Environment**

-   Device: Moto G Stylus
-   OS: [Android 11]
-   APP: [0.8.0]

**2. Describe the bug**
When I add a feed it pulls the most recent articles just fine but doesn't update them. For example, if I add xkcd.com/rss.xml I get the four most recent comics but no new comics. This affects all feeds I have added.

**Comment by Ashinch** [comment]
Hi, @Cynosure-null 

Version 0.8.1 has been released and I think it may solve your issue.
