### ISSUE TITLE
Read Aloud Integration Method? 

### ISSUE THREAD

**Issue by ihateprogramming88** [Ashinch/ReadYou#801]
Not particularly a feature request, I wanted to work on the read aloud feature. Is there any particular way that you want this implemented?

**Comment by Jackson-Nickk** [comment]
Please use a good neural network based engine so it wouldn't be a robotic and annoying voice reading the text. There are numerous open source read aloud engines out there that you can use.

**Comment by ihateprogramming88** [comment]
Does anyone have any recommendations for neural network engines that can be used?

**Comment by Jackson-Nickk** [comment]
A simple google search brought me to this:

https://github.com/espeak-ng/espeak-ng

They say it's lightweight and low footprint. It even has an android implementation for testing which I tested and it was OK. Its development doesn't seem to be dead as the last commit was 8 days ago.

But that's just my search results, and I am not a developer myself. Please probe this project and search for other TTS models to find the one most suitable.

**Comment by Jackson-Nickk** [comment]
This one also seems interesting:
https://github.com/coqui-ai/TTS

**Comment by Jackson-Nickk** [comment]
Android its own API called Google Speech Recognition & Synthesis. Third party apps can use the built in API to get accessibility features. But it is not as good as other neural models. And also, it relies on the provided API from android,  which means if you're using a custom ROM android that ripped this API out, the ReadYou app cannot produce TTS on its own.

**Comment by Jackson-Nickk** [comment]
This one also has good results:

https://github.com/rendchevi/nix-tts

But its development seems dead.

**Comment by Jackson-Nickk** [comment]
Mozilla has its own TTS engine too:

https://github.com/mozilla/TTS

It's also good but I don't know if it's lightweight or suitable for this job. Pocket text to speech feature is good, but I couldn't find any evidence that Pocket is using Mozilla's TTS model or not.

This one also didn't see the charm of development in 3 years. I don't know how that would effect you or the implementation. But you can always train the model yourself I guess.

**Comment by candideu** [comment]
Reeder is another FOSS RSS reader that does TTS read aloud pretty well, but I'm not sure what library is being used, and there's only one voice: https://github.com/spacecowboy/Feeder

Another engine to look into is Piper TTS: https://github.com/rhasspy/piper

My only other suggestion, from a user experience perspective, would be to highlight the paragraph being read, and having the ability to click on a paragraph to go back to it. This way users can replay or skip to the sections of their choice.

Here are some examples from other reading apps:

### [Read Aloud](https://readaloud.app/)
![image](https://github.com/spacecowboy/Feeder/assets/55474996/82d2a3ca-29db-472d-8b31-177aefe8d7fd)

### [AblePlayer](https://ableplayer.github.io/ableplayer)
![https://ableplayer.github.io/ableplayer/demos/video3.html](https://github.com/spacecowboy/Feeder/assets/55474996/1e36ab48-bb55-489f-8792-2c1b08be6165)

### [Hyperaudio](https://hyperaudio.github.io/hyperaudio-lite-editor)
![https://hyperaudio.github.io/hyperaudio-lite-editor/#hypertranscript=22.1,22.3](https://github.com/spacecowboy/Feeder/assets/55474996/8262654b-eee7-4bfa-9034-c3521d9dda2f)

**Comment by ihateprogramming88** [comment]
Great, thanks for the input, I'll do some research and decide what is best suited. Hopefully will get started soon.

**Comment by Ashinch** [comment]
Temporary solution: Utilize the ability to read aloud in webview.

**Comment by Ashinch** [comment]
#801

**Comment by ihateprogramming88** [comment]
Awesome, nice stuff, I have downloaded the latest build, how do I use read aloud. I can see bionic reading is working nicely. Just can't figure out how to use read aloud, WebView is enabled. @Ashinch

**Comment by Ashinch** [comment]
> Awesome, nice stuff, I have downloaded the latest build, how do I use read aloud. I can see bionic reading is working nicely. Just can't figure out how to use read aloud, WebView is enabled. @Ashinch

In Webview, needs select text and expand text tool to tap "Read aloud" button.

I‘m looking for a more convenient way to trigger.

**Comment by ihateprogramming88** [comment]
I can't seem to get this to work on GrapheneOS, do you need any extra applications installed, I have google speech synthesis installed but when I delete the text in WebView no option pops up with read aloud at the moment on latest nightly build.

**Comment by ihateprogramming88** [comment]
Is there any update on the read aloud inteegration?
