### ISSUE TITLE
How to fix freshrss login 405 not allowed error

### ISSUE THREAD

**Issue by xRahul** [Ashinch/ReadYou#830]
when I use freshrss self hosted server with user/pass, I see the toast, 405 not allowed.

I was able to login via greader though to same freshrss server and user/pass.

Any doc on what I need to do, or what I am not doing correctly?

**Comment by jaygz316** [comment]
In settings under authentication, turn on allow API access
then go to profile and input an API password
finally, when you go to input your info into the app, the server should look like his https://yourURL.com/api/greader.php
don't forget the "/api/greader.php"

**Comment by xRahul** [comment]
@jaygz316 In that case I can just use greader option for auth as I'm doing right now.
Why do we have a separate freshrss option then?
