### ISSUE TITLE
RTL Language support

### ISSUE THREAD

**Issue by pokurt** [Ashinch/ReadYou#86]
**1. Environment**

-   Device: [Xiaomi Redmi Note 10 Pro Max]
-   OS: [Android 12]
-   APP: [0.8.0]

**2. Describe the feature request**

currently rtl languages like arabic and dhivehi shows from left to right which makes for us readers hard to read the articles.

**Comment by pokurt** [comment]
![Screenshot_2022-05-29-12-38-40-384_me.ash.reader.jpg](https://user-images.githubusercontent.com/43902347/170857547-32a3bcae-daaf-45a9-a705-936be2ce1a3f.jpg)

an example of how it looks right now

**Comment by pokurt** [comment]
feed link: https://vnews.mv/rss
site: https://vnews.mv

**Comment by Ashinch** [comment]
Thanks for opening this issue, I completely ignored it before!

**Comment by pokurt** [comment]
welcome^^
well, there are many users around the globe who will be willing to use this app :D
while adding rss i would suggest to have a toggle for rtl. because i dont think theres a kotlin library that detects it automatically. thank you for looking up

**Comment by JunkFood02** [comment]
Compose supports content-aware `TextDirection`
See also: RTL support Implementation in [Seal](https://github.com/JunkFood02/Seal/commit/303e6f55e87cfdb7ceedf589869d9bfb63288df6)
