### ISSUE TITLE
articles do not use external font with WebViev renderer

### ISSUE THREAD

**Issue by AnthillSudoku** [Ashinch/ReadYou#881]
**Environment**

-   Device: samsung a52q
-   OS: Android 13
-   APP: 0.11.1 fdroid

** Describe the bug**

1. Settings
2. Color & style
3. Reading page
4. Content renderer = WebViev
5. Reading fonts = external font (choose a working .ttf)

Now the external font is not used to display articles. To do so you have to switch "Content renderer = native component"

**Comment by xuangeyouneihan** [comment]
Not only external fonts, but also custom fonts.
I prefer to set the reading font to Serif, but the default font is still used to display articles.

![Screenshot_2024-11-16-15-11-05-237_me ash reader](https://github.com/user-attachments/assets/be04813e-9126-4ea8-9e7b-e36d5f2768b5)
