### ISSUE TITLE
Reddit RSS images open web browser when tapped on

### ISSUE THREAD

**Issue by CeruleanDerpo** [Ashinch/ReadYou#895]
**1. Environment**

-   Device: [Pixel 7a]
-   OS: [Android 15]
-   APP: [0.11.0]

**2. Describe the bug**
Some RSS feeds' images such as https://www.reddit.com/r/popular/top.rss open the whole web page when clicked on while opening the image in Read You's full screen image view requiring the user to press back every time and cancel the page load to see the image

**Comment by JunkFood02** [comment]
Duplicate of #878
