### ISSUE TITLE
Feature request: Hide or delete read articles

### ISSUE THREAD

**Issue by alkamine** [Ashinch/ReadYou#926]
I would like to request the ability to hide or delete in feeds articles that have already been read. Currently, the articles in question already read are greyed out, and still remain in the feed along with new unread articles. This makes it a more cluttered user experience once new articles are downloaded and in situations where a feed is updated frequently.

Thank you for your consideration.

**Comment by JunkFood02** [comment]
You can switch to Unread filter(the middle button of the bottom bar) to see only the unread articles. Plus, you can configure the app to automatically delete read articles in Settings - Account - Keep archive articles
