### ISSUE TITLE
Update Interval

### ISSUE THREAD

**Issue by kou9221** [Ashinch/ReadYou#97]
What's the update interval of this app? Im new in rss feed so idk if the site will decide the interval or the app

Edit: cause it seems its not updating my feed

**Comment by Ashinch** [comment]
This application synchronizes every 15 minutes by default.

As to whether there will be new articles, it depends on the rss feed.

**Comment by kou9221** [comment]
> This application synchronizes every 15 minutes by default.
> 
> As to whether there will be new articles, it depends on the rss feed.

I see. I ask because one of subreddit rss feed i put on the app doesnt seem to update, ive try on other app and its working fine. I will investigate this interval thing again and see if my rss feed is the problem.

Thanks for your response...

**Comment by Ashinch** [comment]
@kou9221 Please use the just released version 0.8.1 for testing.😀

**Comment by kou9221** [comment]
> @kou9221 Please use the just released version 0.8.1 for testing.😀

The feed synchronized but the interval is not 15 minutes but 1 hour? I just got a notification in this while browsing on reddit.

Btw im using the 0.8.1 version one

**Comment by Ashinch** [comment]
@kou9221 Then this is the normal situation. The application will get the article list from the feed every 15 minutes. If there happens to be a new article published, it will be included in the application.☺️
