### ISSUE TITLE
Add an option to change the time format

### ISSUE THREAD

**Issue by ch3thanhs** [Ashinch/ReadYou#98]
**1. Environment**

-   Device: [Pixel 6]
-   OS: [Android 12.1]
-   APP: [0.8.1]

**2. Describe the feature request**

As a user I should be able to change the time format that is displayed in the feed, i.e., the time an article was published. (12-hour format or 24-hour format).

![Image for reference](https://user-images.githubusercontent.com/76928501/172104113-196da26b-96d5-4f00-adcc-bb0247cbafc5.png)

**Comment by kou9221** [comment]
+1 for this

**Comment by Ashinch** [comment]
@ch3thanhs Good suggestion.
